departement-loire-atlantique/jPlatformSocle

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/portal/headerSection.jsp

Ajout du header sans les variantes

Ajout du header standard et de la feuille css pour les icones

---

WEB-INF/data/types/PageCarrefour/PageCarrefour.xml

https://refonte44.atlassian.net/browse/RS-272?atlOrigin=eyJpIjoiZGUzNzFmMmNmNTgzNDE0Y2I5ZWEyNTJiMjJmOWZiZmMiLCJwIjoiaiJ9

Fix : le champ "image" doit être obligatoire pour Page Carrefour

---

WEB-INF/data/types/FicheActu/FicheActu.xml
WEB-INF/data/types/FicheAide/FicheAide.xml
WEB-INF/data/types/FicheArticle/FicheArticle.xml
WEB-INF/data/types/FicheLieu/FicheLieu.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop

Généralisation de certaines racines de catégories pour la lisibilité et la cohérence des données

Refacto. des propriétés de racines de catégories

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/tags/levelTwoMenu.tag
WEB-INF/tags/menuLink.tag
plugins/SoclePlugin/jsp/portal/headerSection.jsp
plugins/SoclePlugin/jsp/portal/welcomeSectionPortal.jsp

Actions suivant le traitement du ticket Jira RS-283

[Feat. / Fix] Intégration retours access. + ouverture des liens de menu dans un nouvel onglet 

---

plugins/SoclePlugin/jsp/reprise/repriseFicheLieu.jsp

Fix : reprise fiche lieu correction virgule et cedex

Fix : Correction virgule et cedex

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/levelTwoMenu.tag
WEB-INF/tags/titleSimple.tag
plugins/SoclePlugin/jsp/portal/socialNetworksHeader.jspf
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf
plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateBreadcrumb.jsp

Inclusion de la fiche actu, fiche article, breadcrumb (intégré aux deux fiches)

Evol : intégration des mises à jour du design system

---

plugins/SoclePlugin/jsp/portal/headerSection.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

Le script d'ouverture de modale a été mis à jour sur le design system. J'ai ajouté un tag précis sur les boutons qui sont censés ouvrir une modale afin que le focus revienne sur ces boutons à la fermeture de la modale / de l'overlay

Evol : généralisation du script d'ouverture de modale

---

WEB-INF/data/types/FaqDEP44/FaqDEP44-templates.xml
WEB-INF/data/types/FaqDEP44/FaqDEP44.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop

https://refonte44.atlassian.net/browse/RS-679

Creation type faq

---

WEB-INF/tags/categoryList.tag
plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateMenuCollapseFullDisplay.jsp

Changement du test sur la présence de contenu principal

Fix : RS-753 Collapser

---

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateBreadcrumb.jsp

Adaptation pour fonctionner aussi sur le site handicap.
On supprime le "skip 2" dans  le <jalios:foreach> car ce n'est pas bien géré si on n'a que 2 ancestres ou moins. A la place on supprime les 2 premiers ancêtres en amont, dans la Collection

Evol : fil d'Ariane

---

WEB-INF/data/types/FicheLieu/FicheLieu.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

Integration fiche lieu retour acc

---

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java
WEB-INF/plugins/SoclePlugin/plugin.xml

Si un target "_blank" est détecté sur les liens des blocs wysiwyg alors ajouter automatiquement " - nouvelle fenêtre" dans le title.

Ajout d'un WysiwygPoliciFilter pour vérifier le contenu des "title"

---

WEB-INF/data/types/FaqAccueil/FaqAccueil.xml
plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp

FIX champ nombre de questions affiches
FIX remplacer titre par champ description
FIX quick fix recuperation email

FIX type faq accueil

---

WEB-INF/data/types/FaqAccueil/FaqAccueil.xml
plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp

fix emplacement affichage champ description

Integration faq retour fonctionnel

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/VideoUtils.java
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/insertionUnifiee/mediaTemplateContent.jsp
plugins/SoclePlugin/jsp/insertionUnifiee/unifiedInsertContent.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplay.jsp
plugins/SoclePlugin/types/FileDocument/doFileDocumentEmbedDisplay.jsp
plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp

Mécanique d'insertion dans les zones wysiwyg.
Gabarits "embed" des vidéos, documents et fiche lieu.
C'est un premier jet. Les gabarits restent à affiner.
La suite consistera à pouvoir insérer des listes de contenus, notamment des docs et fiche lieu.

Mise en place de l'insertion unifiée

---

WEB-INF/data/types/ListeDeContenus/ListeDeContenus.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/insertionUnifiee/listeDeContenusTemplate.jsp
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusContacts.jsp
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusDocuments.jsp
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusFullDisplay.jsp

Création d'un type "ListeDeContenus" pour pouvoir insérer facilement des listes de docs et de contacts (fiche lieu) via l'insertion unifiée, ou directement dans     les pages carrefour par ex pour alimenter la colonne de droite.

Evol RS-770 / RS-860 insertion unifiée

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
WEB-INF/tags/facetteCategorie.tag
WEB-INF/tags/facetteCategorieListElem.tag
plugins/SoclePlugin/jsp/facettes/searchCategoriesLiees.jsp
plugins/SoclePlugin/types/PortletFacetteCategorie/doPortletFacetteCategorieBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-721
https://refonte44.atlassian.net/browse/RS-722

RS 721 - RS 722 portlet facette categorie et categories liees

---

WEB-INF/data/types/FicheAide/FicheAide.xml
WEB-INF/data/types/FicheArticle/FicheArticle.xml
WEB-INF/data/types/Temoignage/Temoignage.xml
WEB-INF/data/types/Video/Video.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/jsp/templates/temoignageTemplate.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideEncadre.jspf

Création d'un type abstrait "Témoignage" dont héritent les types "Video" et "Fiche Article".
Génération de la vignette à partir du champ "image principale"
Intégration dans la fiche aide via un media template

Evol RS-771 : intégration des témoignages dans la fiche aide

---

plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-680

Rs 680 fix faq ds fiche aide

---

WEB-INF/tags/titleSimple.tag
plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf

Déplacement du chapo lorsqu'on a une vidéo à la place de l'image dans le titre de l'article.

Fix RS-775 titre vidéo

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-769

Fix rs 769 fiche aide popin suivre demande

---

WEB-INF/data/types/Video/Video.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/types/Video/doVideoFullDisplay.jsp

Début d'intégration car maquette et JS pas finis.
Refacto du type pour avoir les mêmes noms (images, légende, copyright)  que les autres types de contenus.

Evol RS-858 intégration Fiche vidéo

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-766

Fix rs 766 affichage adresses

---

plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusTuileHorizontale.jsp

Intégration sous forme de media template.
Fonctionnait comme un "usage"

Fix liste de contenus

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/tags/titleDelegation.tag
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-914
Comprends aussi des fix pour la popin suivre une demande de la fiche aide et des petits refactos
*par "adresse ecrire" j'entends les adresses qui comptent "cs" et "cedex" dedans

Fix rs 914 fiche lieu adresse ecrire

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/facetteCategorie.tag
plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-721

Fix rs 721 largeur champ + croix effacer

---

WEB-INF/data/types/Video/Video.xml

Bascule d'onglet pour 2 champs. Super modif !

Fix type vidéo

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheAide/doFicheAideEncadre.jspf

https://refonte44.atlassian.net/browse/RS-926

Fix rs 926 fiche aide titre bon a savoir

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-893

FIX RS-893 fiche lieu affichage horaire et accès

---

plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-922

EVOL RS-922 FAQ ajout bouton plus de questions

---

WEB-INF/classes/fr/cg44/plugin/socle/queryfilter/LuceneQueryFilter.java
WEB-INF/data/types/PortletRechercheFacettes/PortletRechercheFacettes.xml
plugins/SoclePlugin/jsp/facettes/doQueryCids.jspf
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-589

EVOL renseignement union des catégories et union facettes catégories

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-996

Fix rs 996 espace entre plusieurs adresses

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/headerSection.jsp
plugins/SoclePlugin/jsp/portal/home.jsp
plugins/SoclePlugin/jsp/portal/popinSitesEtApplis.jsp
plugins/SoclePlugin/jsp/portal/sitesEtApplis.jspf

Refacto du headerSection.jsp pour éviter les doublons de code. (La popin reprends une partie du code du menu)
Intégration d'une porlet jsp "popin" dans le gabarit de la home page.

Evol : intégration de la popin "sites et applis"

---

WEB-INF/tags/titleDelegation.tag
plugins/SoclePlugin/jsp/portal/headerSection.jsp
plugins/SoclePlugin/jsp/templates/plusRecherche.jsp
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

Dans les <a> uniquement.
Précos accessibilité Franck.

Fix : remplacement des aria-label par des title

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

retours de ce ticket :
https://refonte44.atlassian.net/browse/RS-769

FIX affichage bouton suivre demande

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1001

Fix rs 1001 affichage form faq

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/data/types/FichePublication/FichePublication.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/reprise/repriseFicheMagazine.jsp
plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp

Script de reprise "one shot" (via URL directe du script, pas de lien dans espace Admin)
Nouveau type de contenu "Fiche Publication"
Gabarit JSP

Evol Magazine RS-853

---

WEB-INF/data/types/PortletFacetteCategoriesLiees/PortletFacetteCategoriesLiees.xml
WEB-INF/tags/facetteCategorie.tag
plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1002

FIX ordre categories affiches + racine cat contribution categories lies

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1024

FIX+REFACTO creation titre lien plus de detail

---

plugins/SoclePlugin/jsp/templates/temoignageTemplate.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideEncadre.jspf

https://refonte44.atlassian.net/browse/RS-1022

Fix rs 1022 retours accessibilite fiche aide

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1024

FIX integration texte alternatif

---

WEB-INF/tags/figurePicture.tag
jcore/doEmptyFooter.jspf
plugins/SoclePlugin/jsp/portal/blocMenuPDCV.jspf
plugins/SoclePlugin/jsp/portal/headerSection.jsp
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusContacts.jsp

Quelques corrections suite warning W3C ou remarques Franck

Fix accessibilité

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheSAAD/doFicheSAADFullDisplay.jsp

utilisation de propriétés paramétriques pour simplifier le code et avoir qqch de correct si multilangues

Refacto Fiche SAAD

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/facetteCategorie.tag
WEB-INF/tags/facetteCategorieListElem.tag
plugins/SoclePlugin/types/PortletFacetteCategorie/doPortletFacetteCategorieBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-722

FIX facette categories liees

---

plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp

Evol : intégration marqueurs stats Fiche Publication

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1049
Pull request refait car le précédent merge n'a pas fonctionné

FIX suppresion affichage couverture geographique fiche lieu

---

plugins/SoclePlugin/types/SeniorCitizensEstablishment/doSeniorCitizensEstablishmentFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-847

FIX suppression partie recuperation CLIC plus proche

---

WEB-INF/data/types/Dossier/Dossier.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/AccueilAnnuaireAgenda/doAccueilAnnuaireAgenda_Agenda.jsp
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-939

Evol rs 939 creation integration type dossier

---

plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf

Changement de style au niveau de la colonne droite et des onglets pour intégrer une grille moins large dans le corps des contenus.

Evol DS : largeur de la grille

---

plugins/SoclePlugin/jsp/cards/doCantonCard.jsp
plugins/SoclePlugin/jsp/cards/doCityCard.jsp
plugins/SoclePlugin/jsp/cards/doElectedMemberCardFull.jsp
plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheSAADCard.jsp
plugins/SoclePlugin/jsp/cards/doSeniorCitizensEstablishmentCard.jsp

Uniformisation et modification des id en dur ou manquants.
Prendre comme principe : 
id="tuileTYPE_DE_TUILE<%= pub.getId() %>"

Refacto des id des tuiles

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/cards/doCantonCardFull.jsp
plugins/SoclePlugin/jsp/templates/doFichePublicationTuileHorizontaleGrey.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp
plugins/SoclePlugin/types/FicheSAAD/doFicheSAADFullDisplay.jsp
plugins/SoclePlugin/types/SeniorCitizensEstablishment/doSeniorCitizensEstablishmentFullDisplay.jsp

Uniformisation des différents gabarits.
Utiliser uniquement cette prop paramétrique désormais : 
jcmsplugin.socle.lien.site.nouvelonglet: Site web : {0} - nouvelle fenêtre

Fix accessibilité : title des lien

---

WEB-INF/data/types/Lien/Lien.xml
WEB-INF/data/types/Video/Video.xml
plugins/SoclePlugin/jsp/templates/temoignageTemplate.jsp
plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp

Concerne les FAQ et les tuiles "Témoignage"

Retours accessibilite

---

plugins/SoclePlugin/jsp/addCustomCss.jsp
plugins/SoclePlugin/jsp/addCustomJs.jsp
plugins/SoclePlugin/jsp/templates/plusRecherche.jsp
plugins/SoclePlugin/jsp/templates/plusRechercheLien.jspf
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

Petits fix qui serviront pour stats et pages erreurs
Fix accessibilité "contenus les + consultés"

Fix divers

---

plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-939

FIX RS-939 retours fonctionnels full display dossier

---

plugins/SoclePlugin/jsp/portal/abonnementNewsletterFooter.jspf
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1022

FIX retours accessibilites

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doElectedMemberCardFull.jsp

https://refonte44.atlassian.net/browse/RS-850

Evol rs 850 intégration fiche élu

---

WEB-INF/tags/phone.tag
plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp

Rajout du marqueur sur les liens et sur le numéro de téléphone.
Evol du tag "phone" pour ajouter le marqueur.

Evol : stats sur encadrés contacts

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/ElectedMember/doElectedMemberFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-850

FIX rajout jsp full display manquant

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/tags/pdcvSearchFields.tag
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationPdcv.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletSearchPdcv.jsp

Le comportement de recherche pour cette tuile n'est pas encore développé. Il faudra le mettre en place plus tard. Ce PR est là juste pour la déclaration du gabarit

Evol : intégration graphique tuile PDCV (pas de recherche)

---

WEB-INF/tags/facetteCategorie.tag
plugins/SoclePlugin/jsp/portlet/portletFacetteAutoCompletion.jspf
plugins/SoclePlugin/types/PortletFacetteMotcle/doPortletFacetteMotcleBoxDisplay.jsp
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1092

FIX ajout attribut data-auto-submit="true" qd c'est une facette filtre

---

WEB-INF/data/types/SeniorCitizensEstablishment/SeniorCitizensEstablishment.xml
plugins/SoclePlugin/types/SeniorCitizensEstablishment/doSeniorCitizensEstablishmentFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-847
Pour SeniorCitizensEstablishment.xml, tous les champs ont été mis dans un nouvel onglet "Contenu"

FIX retours fonctionnels etablissement personnes agees

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/types/Delegation/doDelegationFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-859

EVOL ajout full display type delegation

---

plugins/SoclePlugin/types/AccueilDelegation/doAccueilDelegationFullDisplay.jsp

Le nom du thème avait changé et je n'avais pas reporté cette modifi ici.

Fix carousel accueil délégation

---

plugins/SoclePlugin/jsp/portal/headerSection.jsp

Ajout des ID sur les boutons
Ajout d'une classe css pour adaptation header handicap.

Fix ouverture menu

---

plugins/SoclePlugin/jsp/portal/blocMenuPDCV.jspf
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1022

FIX retours accessibilite

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/ElectedMember/doElectedMemberFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-850

FIX retours fonctionnels fiche élu

---

WEB-INF/tags/titleNoImage.tag
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

Ajustement des colonnes du bloc vert + refacto car un tag existait pour gérer ce type de titre.
Gestion du sous-titre dans le tag.

Fix RS-1026 - Fiche action éducative

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1108

FIX fiche aide cache champ duree si vide

---

plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf

https://refonte44.atlassian.net/browse/RS-1103

FIX carrousel reduction nbr tuiles simultanees au nbr tuile total

---

plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1089

EVOL ajout champ cache avec parametre affichage contenu

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/data/types/FicheArticle/FicheArticle.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/addCustomCss.jsp
plugins/SoclePlugin/jsp/addCustomJs.jsp
plugins/SoclePlugin/types/FileDocument/doFileDocumentEmbedDisplay.jsp

Cf règle dans javadoc de la méthode formatAdresseEcrire

Fix RS-1107 :  revoir la règle d'affichage de l'adresse postale

---

plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp

Comme vu durant le daily, les légendes et les copyright ne doivent pas être affiché dans le carrousel, donc le ticket a été abandonné. 
Néanmoins, j'ai fait un petit refacto sur le fichier qui était concerné par le ticket.

REFACTO tuileVerticale

---

WEB-INF/data/types/Contact/Contact.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop

MAJ des propriétés de catégorie + suppr prop inutile

Fix type contact

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

https://refonte44.atlassian.net/browse/RS-850

FIX espaces et tirets ds fiche elu

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1126

FIX bug affichage description fiche lieu

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/data/types/FicheLieu/FicheLieu.xml
plugins/SoclePlugin/jsp/cards/doFicheLieuCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheLieuResultCard.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

- services du dép : passage de booleen à catégorie
- refacto suite changement ci-dessus
- fix format d'adresse postale + ajout méthode adresse physique

Fix + evol Fiche Lieu

---

plugins/SoclePlugin/jsp/cards/doContactCard.jsp
plugins/SoclePlugin/jsp/reprise/repriseContenuContact.jsp

Prise en compte du téléphone fixe et du mobile (le mobile n'était pas pris en compte).

Fix RS-962 : reprise téléphones des animateurs sportifs

---

plugins/SoclePlugin/jsp/cards/doFicheLieuCard.jsp
plugins/SoclePlugin/jsp/cards/doSeniorCitizensEstablishmentCard.jsp

OK accessibilité pour mettre un <li> si un seul numéro.
J'ai juste mis à jour les tuiles intégrant des tel.

Refacto : gestion des tel en liste (tuiles)

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf
plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp

Evol CSS impression : ajout de styles

---

plugins/SoclePlugin/types/SeniorCitizensEstablishment/doSeniorCitizensEstablishmentFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-847

FIX affichage question conseil vide

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/tags/facetteAutoCompletion.tag
plugins/SoclePlugin/types/PortletFacetteAdresse/doPortletFacetteAdresseBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCanton/doPortletFacetteCantonBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCategorie/doPortletFacetteCategorieBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCommune/doPortletFacetteCommuneBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCommuneAdresseLiee/doPortletFacetteCommuneAdresseLieeBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationPdcv.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletSearchPdcv.jsp
plugins/SoclePlugin/types/PortletFacetteTitre/doPortletFacetteTitreBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1138

REFACTO portletFacetteAutoCompletion.jspf to facetteAutoCompletion.tag

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1135

FIX fiche lieu - condition affichage pour qui

---

WEB-INF/tags/facetteAutoCompletion.tag
WEB-INF/tags/pdcvSearchFields.tag
plugins/SoclePlugin/types/FicheAide/doFicheAideFormSectorisation.jspf
plugins/SoclePlugin/types/PortletFacetteAdresse/doPortletFacetteAdresseBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCanton/doPortletFacetteCantonBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCategorie/doPortletFacetteCategorieBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCommune/doPortletFacetteCommuneBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCommuneAdresseLiee/doPortletFacetteCommuneAdresseLieeBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationPdcv.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletSearchPdcv.jsp
plugins/SoclePlugin/types/PortletFacetteTitre/doPortletFacetteTitreBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1137

Refacto rs 1137 factoriser code recherche pres de chez vous

---

plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1130
Xavier m'a demandé de passer l'info non plus par un input caché mais par un data

FIX transmission d'info au js pour l'affichage des resultats au clic

---

plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationPdcv.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletSearchPdcv.jsp

https://refonte44.atlassian.net/browse/RS-1137

FIX attribut dataMode en double et manque isLarge

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1022

FIX liens retours à l'onglet avec le clavier

---

plugins/SoclePlugin/jsp/cards/doCantonCard.jsp
plugins/SoclePlugin/jsp/cards/doCantonCardFull.jsp

En utilisant le bon comparateur...

Fix : ordre des membres sur les tuiles Canton

---

WEB-INF/data/types/PortletRechercheFacettes/PortletRechercheFacettes.xml
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettePdcv.jsp
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1088

FIX transmission info geojson au js

---

WEB-INF/tags/facetteAutoCompletion.tag

https://refonte44.atlassian.net/browse/RS-588

Fix rs 588 champ commune adresse liees

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/facetteAutoCompletion.tag
plugins/SoclePlugin/types/PortletFacetteAdresse/doPortletFacetteAdresseBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1094

Fix rs 1094 update champs lies

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

petite oubli dans du fix précédent sur les geojson

FIX url des geojson en propriete du module

---

plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationPdcv.jsp
plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletSearchPdcv.jsp

Rajout du "title" + correctif balises supprimées précédement

Fix portlet "PDCV" Menu + sidebar

---

plugins/SoclePlugin/jsp/portal/handicap/home.jsp
plugins/SoclePlugin/jsp/portal/home.jsp
plugins/SoclePlugin/jsp/portal/welcomeSectionPortal.jsp

Fix bouton "haut de page"

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/facetteAutoCompletion.tag
WEB-INF/tags/facetteCategorie.tag
WEB-INF/tags/facetteCategorieListElem.tag
plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteMotcle/doPortletFacetteMotcleBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1121

FIX integration des facettes

---

WEB-INF/tags/levelTwoMenu.tag
plugins/SoclePlugin/jsp/portal/blocMenuPDCV.jspf
plugins/SoclePlugin/jsp/portal/headerSection.jsp

Sur les différentes section du menu, masquées par défaut.

Fix accessibilité menu : ajout de aria-hidden

---

WEB-INF/tags/facetteAutoCompletion.tag
WEB-INF/tags/facetteCategorie.tag
plugins/SoclePlugin/types/PortletFacetteAgendaAccessibilit/doPortletFacetteAgendaAccessibilitBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteAgendaDate/doPortletFacetteAgendaDateBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCommuneAdresseLiee/doPortletFacetteCommuneAdresseLieeBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteMotcle/doPortletFacetteMotcleBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1196

Fix rs 1196 name des facettes

---

plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1094

FIX probleme name facette categories liees

---

WEB-INF/tags/tuileContenuEnAvant.tag

Fix niveau de titre sur tuile mise en avant

---

plugins/SoclePlugin/types/FileDocument/doFileDocumentFullDisplay.jsp

Fichier manquant pour gabarit Full

Fix filedocument

---

plugins/SoclePlugin/jsp/templates/temoignageTemplate.jsp

https://refonte44.atlassian.net/browse/RS-680

FIX remplir alt de l'image par le titre si le texte alt est vide

---

WEB-INF/data/types/FicheActionEducative/FicheActionEducative.xml
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1189

EVOL 3 champs plus obligatiore ds fiche action educative

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/message.tag
plugins/SoclePlugin/jsp/doMessageBoxCustom.jspf
plugins/SoclePlugin/jsp/forms/doFormHeader.jspf
plugins/SoclePlugin/types/ContactForm/editFormContactForm.jsp

- modif de la message box pour les messages de succes/erreur (modifs DS)
- mise en prop de textes qui étaient en dur

Modifs formulaire contact

---

WEB-INF/tags/facetteCategorie.tag
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1094
C'est un minor fix indépendant du ticket. Ce dernier reste en suspens car il reste un bug js à régler. Or, cela impliquera peut-être des modifs au niveau de l'intégration jcms.

FIX NPE ds accueil recherche facette

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/infolocale/RequestManager.java
WEB-INF/data/types/PortletAgendaInfolocale/PortletAgendaInfolocale.xml
WEB-INF/data/types/PortletFacetteAgendaCategorie/PortletFacetteAgendaCategorie.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
WEB-INF/tags/facetteAgendaCategorieListElem.tag
WEB-INF/tags/facetteCategorie.tag
plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleFacettes.jsp
plugins/SoclePlugin/types/PortletFacetteAgendaCategorie/doPortletFacetteAgendaCategorieBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCategorie/doPortletFacetteCategorieBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteCategoriesLiees/doPortletFacetteCategoriesLieesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1158
IMPORTANT, la partie thématique personnalisées avec l'utilisation du champ `groupe de thématiques personnalisées` reste à faire

Evol rs 1158 facette categorie agenda

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/ContactFormDataController.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/forms/doFormFooter.jspf
plugins/SoclePlugin/jsp/mail/formulaireContactTemplate.jsp
plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp

- fix accessibilité champs autocomplete
- tel non obligatoire
- rajout de la commune dans le mail
- ajout d'une méthode de calcul de la commune à partir du CP
- portlet wysiwyg pour texte RGPD en bas du form

Fix contact form

---

plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp

interpretation des champs wysiwyg.

Fix FAQ - RS-1216

---

plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettePdcv.jsp

Supprimer la mention puisqu'elle apparait dans l'encadré vert
(commit précédent : https://github.com/departement-loire-atlantique/jPlatformSocle/pull/448/commits/46f778979d00b90b19520f8d7df1507baea057fc)

Fix portlet PDCV : mention obligatoire

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/CandidatureFormDataController.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/CandidatureSpontaneeFormDataController.java
WEB-INF/data/types/CandidatureForm/CandidatureForm.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/mail/formulaireCandidatureSpontaneeTemplate.jsp
plugins/SoclePlugin/types/CandidatureForm/doEditCandidatureForm.jsp
plugins/SoclePlugin/types/CandidatureForm/editFormCandidatureForm.jsp
plugins/SoclePlugin/types/CandidatureSpontaneeForm/doEditCandidatureSpontaneeForm.jsp
plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleTechnique.jspf
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp

Intégration du formulaire de réponse à une offre
Refacto sur les autres formulaires (champs obligatoires, propriétés)

Evol : formulaire candidature

---

plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf

Si pas de chapo, bug d'affichage

Fix onglets fiche article (RS-1229)

---

plugins/SoclePlugin/types/Carousel/doCarouselSwiperOneBlocFullDisplay.jsp

Affichage du bouton pause par défaut.

Fix bouton lecture carrousel

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop

Intégrer les tuiles des fiches publications (RS-1174)

Evol : déclaration d'un gabarit de tuile pour moteur à facette

---

plugins/SoclePlugin/jsp/facettes/doRetourListe.jspf
plugins/SoclePlugin/types/ElectedMember/doElectedMemberFullDisplay.jsp
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

Gère les styles pour les 2 cas de figures : arrivée depuis le moteur à facette ou depuis le moteur global

fix bouton retour liste (RS-1237)

---

plugins/SoclePlugin/types/CarouselElement/doCarouselElementFullDisplay.jsp

Copie du gabarit full par défaut dans le module.

hotfix : carousel element

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/FichePublication/doFichePublicationEmbedDisplay.jsp

Rajout d'un gabarit spécifique pour l'inclusion dans les wysiwyg

Evol : gabarit "embed" pour fiche publication (insertion unifiée)

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/City/doCityFullDisplay.jsp
plugins/SoclePlugin/types/PortletSearch/doPortletSearchHeader.jsp
plugins/SoclePlugin/types/PortletSearch/query.jsp

Intégration dans les formulaires de recherche + mise en propriété de la valeur.

Evol : pouvoir activer/désactiver la réécriture d'URL

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/rgpd/orejimeConfig.jsp

Intégration du script en début de <body>
Propriétés de modules pour gérer les textes, labels, urls.

Evol : intégration bandeau RGPD (orejime)

---

plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleFacettes.jsp
plugins/SoclePlugin/types/PortletFacetteAgendaAccessibilit/doPortletFacetteAgendaAccessibilitBoxDisplay.jsp
plugins/SoclePlugin/types/PortletFacetteAgendaDate/doPortletFacetteAgendaDateBoxDisplay.jsp

Le fichier "doPortletAgendaInfolocaleFacettes" a subit un formatting intégral. C'était vraiment pas propre visuellement de ce que j'ai pu constater.

1300 - 1305 : fix graphique formulaire facettes agenda

---

WEB-INF/data/types/PressCommunique/PressCommunique.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/PressCommunique/doPressCommuniqueFullDisplay.jsp

Petite spécificité avec l'intégration d'un carrousel dynamique.

PR gabarit "full" des communiqués de presse (RS-854)

---

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateBreadcrumb.jsp

Réponse au problème sous le site handicap où le nv2 n'est pas utilisé

1256 - autoriser les liens cliquables sur le nv1 du fil d'ariane

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/cardPictureCommons.jspf

Tentative de build travis n'2. Premier essai échoué -> n'a pas pu récupérer le ZIP généré pour build

Evol : 1252 - Format d'image 'card' pour les tuiles

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/data/types/PortletFaq/PortletFaq-templates.xml
WEB-INF/data/types/PortletFaq/PortletFaq.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/posezUneQuestion.jsp
plugins/SoclePlugin/jsp/portal/welcomeSectionPortal.jsp
plugins/SoclePlugin/types/FaqAccueil/doFaqForm.jspf

Permet de mettre en avant une FAQ dans telle ou telle catégorie ou branche de catégories. Se manifeste par la présence d'un bouton "Posez une question" en bas d'écran.
Déclaration du nouveau type de portlet "PortletFaq"
Calcul de la présence ou non du bouton
Intégration dans le gabarit de portail

Evol : bouton "poser question" (RS-930)

---

plugins/SoclePlugin/jsp/reprise/contenusSansGeoloc.jsp

Page qui liste les contenus non géolocalisés, classés par types.
Sert uniquement aux admin.

Evol : page de controle des contenus non géolocalisés (RS-1298)

---

WEB-INF/classes/fr/cg44/plugin/socle/LiensUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/portal/socialNetworksShare.jspf
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp
plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp

- paramétrage des différents réseaux sociaux
- activation ou non des fonctions de partage
- jspf + classe de génération des liens de partage
- intégration dans les gabarits full

Evol : intégration du composant "Partagez cette page" (RS-979)

---

WEB-INF/data/types/Dossier/Dossier.xml
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp

Intégration du bloc "sur le même thème" pour les types "dossier" et "actus".
Réorganisation du type "dossier" en onglets dans le formulaire d'édition.

Evol : "Sur le même thème"

---

WEB-INF/classes/fr/cg44/plugin/socle/LiensUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

Propriété paramétrique pour le lien mailto

Fix : lien de partage par mail

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp
plugins/SoclePlugin/types/PressCommunique/doPressCommuniqueFullDisplay.jsp

Classement par date de publication

Fix : tris des publications "sur le même thème"

---

WEB-INF/tags/facetteCategorieListElem.tag

Modification du test d'affichage / masquage des inputs.

Fix tag catégories

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/PressCommunique/doPressCommuniqueFullDisplay.jsp

Changement de branches de catégories
Ajout marge bouton

Fix communiques presse

---

WEB-INF/classes/fr/cg44/plugin/socle/EmploiUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/CandidatureFormDataController.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp

Classe utilitaire dédiée + refacto
Envoi de mail au format texte uniquement.
Log d'erreur en cas de mauvais paramétrage des props.

Fix form candidature

---

plugins/SoclePlugin/types/City/doCityFullDisplay.jsp

Correction de liens.
Présentation en liste.

Fix fiche commune

---

WEB-INF/tags/message.tag
plugins/SoclePlugin/jsp/doMessageBoxCustom.jspf

Mini Fix : messages formulaires

---

WEB-INF/classes/fr/cg44/plugin/socle/LiensUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf
plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf

Revue de la position du bloc dans le DOM
Ajout d'un compte twitter pour loire-atlantique.

Fix "partagez cette page"

---

WEB-INF/data/types/ElectedMember/ElectedMember.xml

Suppression de 3 champs non utilisés.

Refacto type elu (RS-1203)

---

WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/CandidatureSpontaneeFormDataController.java

On générait des fichiers de même nom entrainant une exception.
Suppression de code de debug.

Hotfix candidatures

---

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateFooter.jsp

Pas de lien dans le footer quand lien pointe sur la page courante.

Fix accessibilité footer (RS-1360)

---

WEB-INF/data/types/Action/Action.xml
WEB-INF/data/types/OrganismeGestionnaire/OrganismeGestionnaire-templates.xml
WEB-INF/data/types/OrganismeGestionnaire/OrganismeGestionnaire.xml
WEB-INF/data/types/SportCommittee/SportCommittee-templates.xml
WEB-INF/data/types/SportCommittee/SportCommittee.xml
WEB-INF/data/types/Timeline/Timeline-templates.xml
WEB-INF/data/types/Timeline/Timeline.xml
WEB-INF/data/types/TimelineElement/TimelineElement-templates.xml
WEB-INF/data/types/TimelineElement/TimelineElement.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/PortletFacetteAdresse/doPortletFacetteAdresseBoxDisplay.jsp

- Rajout de types de contenus présents dans le store mais pas encore déclarés.
Il faudra les reprendre à terme et si on fait un nettoyage de store ils seront supprimés.
- Renommage prop + appel de la prop, car génération d'erreur au démarrage.

Hot fix store errors

---

plugins/SoclePlugin/jsp/rgpd/orejimeConfig.jsp

Modif label + description.
Note : certains label sont gérés en multilangue directement dans le JS. A traiter ultérieurement.

Fix : config orejime

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doEvenementInfolocaleVerticalCardCarrousel.jsp
plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleBoxDisplay.jsp

Inclut un correctif d'une méthode Java ! C'est gratuit :)

1386 - Utilisation du bon gabarit vertical pour le carrousel agenda

---

WEB-INF/data/types/FicheEmploiStage/FicheEmploiStage.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp

- Rajout des champs : domaines métiers, email spécifique et intro modalités
- Champs contacts RH et métier en multivalués
- Adaptations du gabarit full + changement règle affichage modalités par défaut.

Evol : fiche emploi/stage

---

plugins/SoclePlugin/types/CandidatureForm/doEditCandidatureForm.jsp
plugins/SoclePlugin/types/CandidatureSpontaneeForm/doEditCandidatureSpontaneeForm.jsp

Fix candidature : champ obligatoire

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/CandidatureSpontaneeFormDataController.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/FicheEmploiStageDataController.java
WEB-INF/data/types/FicheEmploiStage/FicheEmploiStage.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/CandidatureForm/doEditCandidatureForm.jsp
plugins/SoclePlugin/types/CandidatureForm/editFormCandidatureForm.jsp
plugins/SoclePlugin/types/FicheEmploiStage/boutonCandidature.jspf
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp

- Ajout de champs
- Modif du gabarit front (conditions d'affichages)
- Ajout d'un datacontroller

Evol candidatures

---

WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/FicheEmploiStageDataController.java
plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp

Date expiration calculée auto, en fonction de la date limite de dépot de la candidature

Hot fix : datacontroller + tuile

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/Show/doShowFullDisplay.jsp

Gabarit full + propriétés pour les labels

Evol : intégration fiche spectacle

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doSpectacleCard.jsp
plugins/SoclePlugin/types/Show/doShowFullDisplay.jsp

Ajout d'icones, marges, + liens Viméo et Dailymotion

Fix fiche Spectacle

---

WEB-INF/data/types/FicheEmploiStage/FicheEmploiStage.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doSpectacleCard.jsp
plugins/SoclePlugin/types/Show/doShowFullDisplay.jsp

Champs "domaine métier" en multivalué

Fix Fiche emploi + spectacle

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp

Modif de libellé
Modif contenu du mail

hotfix Fiche emploi

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/data/types/FicheEmploiStage/FicheEmploiStage.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp

- rajout de champs email aux contacts
- déclaration d'id de fiches lieux pour mapper les catégorie de Délégation avec les fiches lieu adéquates via nouvelle méthode utilitaire
- renommage de prop + refacto
- modification des conditions d'affichage des modalités de recrutement automatiques

Evol Fiche emploi (RS-1425)

---

plugins/SoclePlugin/jsp/rgpd/orejimeConfig.jsp

Opt out par défaut (cookie déposé avant consentement)

Fix orejime / google analytics

---

plugins/SoclePlugin/jsp/portal/calculetteOA.jsp

Intégration du code du DS dans une JSP pour intégration dans une article.
L'idée de départ était de mettre le code HTML directement dans l'article via l'insertion unifiée de code HTML, mais celui-ci n'est pas bien intégré.
Je tente l'approche via "portlet JSP".
J'ai volontairement laissé les textes en français sans passer par le fr.prop, partant du principe que ce contenu aurait dû être contribué.

Calculette obligation alimentaire (RS-1113)

---

plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf
plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf

Déplacer les réseaux sociaux en-dessous des portlets bas.

Evol portlets bas sur articles

---

plugins/SoclePlugin/jsp/portal/archives/home.jsp
plugins/SoclePlugin/jsp/portal/handicap/home.jsp

Modif du "title" pour les home pages des site Archives et Handicap.

Fix : title des home page

---

plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp

https://refonte44.atlassian.net/browse/RS-1435

FIX RS-1435 champ sujet passe de select radio a select simple

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/jsp/reprise/documentSansContenusLies.jsp
plugins/SoclePlugin/jsp/reprise/documentSansContenusLiesLink.jsp

https://refonte44.atlassian.net/browse/RS-1440

EVOL add script qui liste les documents sans data lie

---

WEB-INF/tags/facetteAutoCompletion.tag

https://refonte44.atlassian.net/browse/RS-1055

FIX retire aria-describedby inutile

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1287

FIX RS-1287 style intro faire une demande de la fiche aide

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/EvenementInfolocale/doEvenementInfolocaleFullDisplay.jsp

Générait des erreurs 500 et bloquait les résulats de recherche

Fix : URL dossier agenda pouvant ne pas être un fichier

---

plugins/SoclePlugin/types/PortletFacetteAgendaDate/doPortletFacetteAgendaDateBoxDisplay.jsp

Un test sur vos postes serait appréciable pour assurer le fonctionnement de la facette date agenda. Il faudrait tester les différentes listes de résultats en prenant certaines dates, et vérifier la cohérence de celles-ci.

1461 - Refacto facette date agenda

---

plugins/SoclePlugin/jsp/reprise/documentSansContenusLies.jsp

https://refonte44.atlassian.net/browse/RS-1440

EVOL RS-1440_ajout_trie_par_type_de_document

---

WEB-INF/data/types/FicheLieu/FicheLieu.xml
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1341

EVOL RS-1341 FicheLieu ajout champ autres lieux associe accueil annuaire

---

plugins/SoclePlugin/jsp/portal/socialNetworksFooter.jspf
plugins/SoclePlugin/jsp/portal/socialNetworksHeader.jspf

https://refonte44.atlassian.net/browse/RS-1473

FIX RS-1473 alignement avec le ds pr les textes cachés RS header/footer

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
plugins/SoclePlugin/jsp/forms/checkArchivesCommunicationAdministrative.jsp
plugins/SoclePlugin/jsp/mail/formulaireArchivesCommunicationAdministrativeTemplate.jsp
plugins/SoclePlugin/jsp/mail/stylesEmail.jsp

Je trouve + clair d'avoir tous les templates de mails, toutes les JSP de contrôle de form au même endroit donc dans Socle mais c'est vrai que c'est dommage d'avoir le code dans 2 modules...
Désolé la classe MailUtils n'est pas très lisible, je n'ai pas bien compris toutes les différences...

Formulaire Archives (communication administrative) : contrôle + mail - RS-1416

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java

Car ce que je pensais être logique ne l'était absolument pas et menait finalement à la création de problèmes :)

Fix recherche agenda : suppression d'un code problématique

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1341

FIX RS-1341 re-fix de l'icone utlise a l'affichage

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/data/types/ContactForm/ContactForm.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/mail/formulaireContactTemplate.jsp
plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp

https://refonte44.atlassian.net/browse/RS-1414
J'ai encore un problème mineur qui traine, quand on soumet le formulaire de contact et que la page avec le formulaire recharge, le champ adresse n'est pas vidé. Quelqu'un saurait pourquoi ?
EDIT : En fait le code js a un bout dédié à sauvegarder les champs ville et adresse, donc c'est un comportement normal.

EVOL RS-1414 ajout formulaire contact archive

---

WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf

https://refonte44.atlassian.net/browse/RS-1437

EVOL RS-1437 ajout style wyziwyg courte citation

---

plugins/SoclePlugin/jsp/portal/archives/footerSection.jsp

https://refonte44.atlassian.net/browse/RS-1278

REFACTO RS-1278 cache temporairement fct abonnement ds footer archive

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1486

Fix rs 1486 fiche lieu accessibilite

---

WEB-INF/data/types/Lien/Lien.xml
plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp

https://refonte44.atlassian.net/browse/RS-1492

Fix rs 1492 lien ds portlet mis en avant

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1487

FIX RS-1487 accessibilite fiche action educative

---

WEB-INF/tags/figurePicture.tag

FIX NPE figurePicture.tag qd pub AND alt sont vides

---

plugins/SoclePlugin/jsp/cards/doContactCard.jsp

FIX Exception ds ContactCard

---

WEB-INF/data/types/FicheActu/FicheActu.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/jsp/templates/temoignageTemplate.jsp

https://refonte44.atlassian.net/browse/RS-1493

EVOL fiche actu peut etre utilise ds portlet mise en avant temoignage

---

WEB-INF/data/types/ChiffresCles/ChiffresCles-templates.xml
WEB-INF/data/types/ChiffresCles/ChiffresCles.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

EVOL RS-1010 ajout encadre chiffres cles

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/cards/doContactCard.jsp
plugins/SoclePlugin/types/Contact/doContactFullDisplay.jsp
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

1528 - harmonisation titre mail + label nous contacter

---

plugins/SoclePlugin/jsp/portal/socialNetworksShare.jspf

https://refonte44.atlassian.net/browse/RS-1524

FIX RS-1524 accessibilite partager la page

---

WEB-INF/data/types/Lien/Lien.xml
WEB-INF/tags/figurePicture.tag
plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp

+ minor fix ds attribut class ds figurePicture.tag
https://refonte44.atlassian.net/browse/RS-1492

FIX_RS-1492_retours_test_fonctionnel

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/portal/sitesEtApplis.jspf
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp

Il s'agit juste de rendre une prop éditable + petit refacto pour en faire un id virtuel.

Evol : paramétrage menu "sites et applis" (RS-1552)

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp

Mise en place d'une prop éditable pour paramétrer les types à afficher dans le carousel.

Evol : carousel "sur le même thème" Fiche actu (RS-1550)

---

WEB-INF/tags/facetteCategorie.tag

https://refonte44.atlassian.net/browse/RS-1537

FIX_RS-1537_accessibilite_facette_categorie_pas_obligatoire

---

WEB-INF/tags/facetteCategorieListElem.tag

https://refonte44.atlassian.net/browse/RS-1538

FIX RS-1538 id label ds facette categorie list elem

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

1521 - Intitulé btn fermeture menu sites applis

---

plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
plugins/SoclePlugin/jsp/templates/tuileHorizontaleGrey.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrandsProjets.jsp

https://refonte44.atlassian.net/browse/RS-1526

FIX RS-1526 accessibilite balises grands projets

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/socialNetworksShare.jspf

https://refonte44.atlassian.net/browse/RS-1524

FIX RS-1524 accessibilite texte cache partage page

---

plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleFacettes.jsp
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1539

FIX RS-1539 accessibilite attribut title rechercher

---

plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrandsProjets.jsp

https://refonte44.atlassian.net/browse/RS-1514

FIX RS-1514 attribut title lien mieux nous connaitre grands projets

---

WEB-INF/tags/facetteCategorieListElem.tag

https://refonte44.atlassian.net/browse/RS-1549

FIX RS-1549 attribut name des radios buttons

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java

https://refonte44.atlassian.net/browse/RS-1492

FIX RS-1492 texte alt lien tuile mis en avant

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

Hotfix Sites et applis : renommage prop

---

plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp

FIX error champ non existant

---

plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1554

FIX RS-1554 fiche action educative remplacer div par p

---

plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf

https://refonte44.atlassian.net/browse/RS-1564

FIX RS-1564 suppression attribut sous titre carrousel

---

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateBreadcrumb.jsp

Problème d'encodage réglé sur github

1543 - aria hidden fil d'ariane - accessibilite

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

https://refonte44.atlassian.net/browse/RS-1294

FIX RS-1294 label champ limiter commune limitrophe

---

plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleFacettes.jsp
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1539

FIX RS-1539 suppression title rechercher ds btn recherche

---

plugins/SoclePlugin/jsp/portal/rechercheFacettes.jsp

https://refonte44.atlassian.net/browse/RS-1546
TODO manip de store/contribution :
dans le portail JSP Collection c_1273916 (COMMUN - Portail page
recherche à facettes), associer les portlets c_1154096 "footer" et
c_1154095 "footerNavigation".

Fix rs 1546 rajout footer ds resultat recherche portail commun

---

WEB-INF/tags/tuileContenuEnAvant.tag

https://refonte44.atlassian.net/browse/RS-1492

FIX RS-1492 title lien externe ds tuile contenu en avant

---

WEB-INF/classes/fr/cg44/plugin/socle/LiensUtils.java
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf
plugins/SoclePlugin/types/PageUtileForm/doEditPageUtileForm.jsp
plugins/SoclePlugin/types/PortletSearch/doPortletSearchHeader.jsp

https://refonte44.atlassian.net/browse/RS-1508
il reste un probleme avec le logo du footer a traiter avec le design
system

FIX RS-1508 validation html page handicap

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/figurePicture.tag
plugins/SoclePlugin/jsp/templates/temoignageTemplate.jsp
plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp

https://refonte44.atlassian.net/browse/RS-1526

FIX RS-1526 alt tuile horizontale + REFACTO getAltTextFromPub

---

WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf

https://refonte44.atlassian.net/browse/RS-1437

FIX RS-1437 style citation courte wysiwyg

---

WEB-INF/plugins/SoclePlugin/plugin.xml

FIX RS-1010 declaration type chiffres cles

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/infolocale/entities/Genre.java
WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java

Si l'événement n'a pas de photo, chercher à utiliser l'image paysage de son genre

1482 - utilisation photo genre event infolocale

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

https://refonte44.atlassian.net/browse/RS-1567

FIX RS-1567 title input recherche pres de chez vous

---

plugins/SoclePlugin/jsp/facettes/commonParamsFacettes.jspf

J'ai vu une petite anomalie qu'il était bon de corriger :)

1575 - prévenir régression taille des champs

---

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java

Ca vous arrive de vous sentir stupide des fois :')
Au moins ça va, on est tous tombés dans le panneau au vu des "approvals"

1021 - fix et maj wysiwygpolicyfilter

---

plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

FIX RS-1010 style encadre chiffres cles

---

plugins/SoclePlugin/jsp/portal/handicap/footerSection.jsp

https://refonte44.atlassian.net/browse/RS-1579

FIX RS-1579 logo footer handicap

---

WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf

https://refonte44.atlassian.net/browse/RS-1512

EVOL RS-1512 ajout syle liste de lien

---

WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf

https://refonte44.atlassian.net/browse/RS-1437

FIX RS-1437 balise style wysiwyg courte citation

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

https://refonte44.atlassian.net/browse/RS-1567

FIX RS-1567 title input pres de chez vous

---

plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1554

FIX RS-1554 fiche action educative remplacer div par p si pas de wysiwyg

---

plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

FIX RS-1010 style chiffres cles

---

plugins/SoclePlugin/types/PortletFacetteAgendaDate/doPortletFacetteAgendaDateBoxDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1580

FIX RS-1580 erreur id duplique input date agenda

---

plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1554

FIX RS-1554 add p autour label cout fiche action educative

---

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java

https://refonte44.atlassian.net/browse/RS-1519

FIX RS-1519 vire les balises <p> qui englobent une balise <div>

---

plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

FIX RS-1010 vide alt des icones chiffres cles

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1554

FIX RS-1554 style fiche action educative

---

WEB-INF/plugins/SoclePlugin/plugin.xml
jcore/doEmptyHeader.jspf

https://refonte44.atlassian.net/browse/RS-979

FIX RS-979 ajout balise meta pour partage twitter

---

WEB-INF/tags/toggle.tag
plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplayContent.jsp

https://refonte44.atlassian.net/browse/RS-1565

FIX RS-1565 style sommaire FAQ et page carrefour

---

plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1582

FIX RS-1582 alt et title ds page magazine

---

plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1457

FIX RS-1457 FicheArticle add affichage page utile selon le champ eponyme

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
plugins/SoclePlugin/jsp/portal/socialNetworksFooter.jspf
plugins/SoclePlugin/jsp/portal/socialNetworksHeader.jspf

https://refonte44.atlassian.net/browse/RS-1577

FIX RS-1577 title lien reseaux footer loire atlantique

---

plugins/SoclePlugin/jsp/portal/socialNetworksCommon.jspf

quickfix lié au pr suivant : https://github.com/departement-loire-atlantique/jPlatformSocle/pull/797

FIX import SocleUtils pr reseaux sociaux

---

plugins/SoclePlugin/jsp/portal/blocMenuPDCV.jspf

https://refonte44.atlassian.net/browse/RS-1522

FIX RS-1522 retire attribut aria-hidden en dur pour le js

---

WEB-INF/tags/levelTwoMenu.tag
plugins/SoclePlugin/jsp/portal/blocMenuPDCV.jspf
plugins/SoclePlugin/jsp/portal/blocMenuRecherche.jspf
plugins/SoclePlugin/jsp/portal/headerSection.jsp
plugins/SoclePlugin/jsp/portal/popinSitesEtApplis.jsp
plugins/SoclePlugin/jsp/portal/posezUneQuestion.jsp
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf
plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1572
https://refonte44.atlassian.net/browse/RS-1587
https://refonte44.atlassian.net/browse/RS-1240
reprise des modifications de ce commit : https://github.com/departement-loire-atlantique/design-system-web/commit/323c83e1b192bdad805da2e663ee2c6c08669382

FIX RS-1572+RS-1587+RS-1240 reprises modifs html du ds

---

plugins/SoclePlugin/types/PortletSearch/query.jsp

https://refonte44.atlassian.net/browse/RS-1533

FIX RS-1533 supprime id et described-by pas pertinent

---

WEB-INF/tags/tuileContenuEnAvant.tag

pas de ticket lié
ligne 100, il y avait un appel à la variable "pub" alors qu'elle n'existait pas. Comme le nom me parait plus approprié que itPub j'ai fait un refacto en même temps que le fix.

FIX + REFACTO nom variable publication ds tuileContenuEnAvant.tag

---

WEB-INF/data/types/FicheActionEducative/FicheActionEducative.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop

https://refonte44.atlassian.net/browse/RS-1379

EVOL RS-1379 ajout champ lieu ds fiche action educative

---

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java

https://refonte44.atlassian.net/browse/RS-1519

FIX RS-1519 regex ds WysiwygPolicyFilter qui vire les espaces apres balise a

---

plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

FIX RS-1010 fix balise <picture> a enlever ds chiffres cles

---

WEB-INF/tags/toggle.tag
plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplayContent.jsp

https://refonte44.atlassian.net/browse/RS-1566
https://refonte44.atlassian.net/browse/RS-1569

FIX RS-1566+RS-1569 add p autour btn toggle ds faq et page carrefour

---

WEB-INF/data/types/FALC/FALC.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doFALCCardFull.jsp

https://refonte44.atlassian.net/browse/RS-997

EVOL RS-997 ajout contenu FALC inserable en wysiwyg

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/FicheAide/doFicheAideEncadre.jspf
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1571
https://refonte44.atlassian.net/browse/RS-1572
j'ai refacto l'indentation de `doFicheAideFullDisplay.jsp`, donc ne pas hésiter à utiliser l'option "hide whitespace changes" pour la review ^^

FIX RS-1571+RS-1572 fiche aide - recuperation modifs du ds

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFormSectorisation.jspf
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

Tracker les clics sur les popin "faire une demande "et "qui contacter"

Fix stats fiche aide RS-1467 / RS-1469

---

plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplayContent.jsp

https://refonte44.atlassian.net/browse/RS-1594

FIX RS-1594 retire attributs html superflus dans balise h3 faq accueil

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp
plugins/SoclePlugin/types/PortletSearch/query.jsp

Personnalisation de la balise <title> pour les résultats de recherche globale + recherche à facettes (pas de ticket)

Stats moteur recherche

---

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java

https://refonte44.atlassian.net/browse/RS-1519

FIX RS-1519 enleve regle wysiwyg policy filter non requis

---

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateMenuCollapseFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1592
J'ai fait un refacto pour l'incrementation ; remplacer des `if`/`else` par des `jalios:if` ; et virer les `<%` `%>` inutils

FIX+REFACTO RS-1592 ajoute title lien document ds menu collapser

---

plugins/SoclePlugin/types/PortletLogin/doPortletLoginEspacePresse.jsp

https://refonte44.atlassian.net/browse/RS-1398

FIX RS-1398 recup modif design system

---

WEB-INF/tags/phone.tag
WEB-INF/tags/titleDelegation.tag
plugins/SoclePlugin/jsp/cards/doContactCard.jsp
plugins/SoclePlugin/types/City/doCityFullDisplay.jsp
plugins/SoclePlugin/types/EvenementInfolocale/doEvenementInfolocaleFullDisplay.jsp
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp
plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp
plugins/SoclePlugin/types/FicheSAAD/doFicheSAADFullDisplay.jspf
plugins/SoclePlugin/types/FicheSAAD/doFicheSAADResultDisplay.jspf
plugins/SoclePlugin/types/PressCommunique/doPressCommuniqueFullDisplay.jsp
plugins/SoclePlugin/types/SeniorCitizensEstablishment/doSeniorCitizensEstablishmentFullDisplay.jsp
plugins/SoclePlugin/types/Show/doShowFullDisplay.jsp

Intégration du plan de marquage sur les numéros de tel, mailto, lien site web (bloc contact vert dans bloc "titre" des différents types de contenus.

Stats plan marquage

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

https://refonte44.atlassian.net/browse/RS-997

FIX RS-997 libelle titre contenu FALC

---

plugins/SoclePlugin/types/PortletLogin/doPortletLoginEspacePresse.jsp

https://refonte44.atlassian.net/browse/RS-1398

FIX RS-1398 input type email doit avoir autocomplete email

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1622

FIX RS-1622 fiche aide remis blocs section pour marging

---

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java
WEB-INF/tags/menuLink.tag
plugins/SoclePlugin/jsp/templates/plusRecherche.jsp
plugins/SoclePlugin/jsp/templates/plusRechercheLien.jspf
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1594

Fix rs 1594 erreurs validation w3

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFormSectorisation.jspf

Renvoyer la commune saisie au marqueur Analytics

Fix formulaire Fiche Aide"qui contacter" RS-1585

---

plugins/SoclePlugin/types/AlertCG/doAlertCGFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1519

FIX RS-1519 alerte ajout balise p autour d'un lien

---

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateMenuCollapseFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1592

FIX RS-1592 menu collapser lien doc ajout target blank

---

WEB-INF/data/types/FicheEmploiStage/FicheEmploiStage.xml

https://refonte44.atlassian.net/browse/RS-1498

FIX RS-1498 undo cat navigation obligatoire

---

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java

https://refonte44.atlassian.net/browse/RS-1624

FIX RS-1624 regle lien externe ignore par accident

---

WEB-INF/tags/phone.tag
plugins/SoclePlugin/jsp/templates/fileDocumentEmbedTemplate.jsp
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp
plugins/SoclePlugin/types/FileDocument/doFileDocumentEmbedDisplay.jsp
plugins/SoclePlugin/types/PortletSearch/doPortletSearchHeader.jsp
plugins/SoclePlugin/types/PortletSearch/query.jsp

Ajout de marqueurs pour tracer : 
- les recherches (moteur global)
- les téléchargements de docs
Modif marqueur sur fiche aide

Fix marqueurs stats

---

plugins/SoclePlugin/jsp/portal/headerSection.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp
plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf

Quelques fix suite à la revue d'accessibilité sur le site handicap.

Fix accessibilite

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1628

FIX RS-1628 fiche aide label bouton modal faire une demande

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop

https://refonte44.atlassian.net/browse/RS-1590

EVOL RS-1590 ajout limite taille fichier a l'upload

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doCarouselCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1417

EVOL RS-1417 ajout contenu integrable diaporama

---

WEB-INF/data/types/Dossier/Dossier.xml
WEB-INF/data/types/FicheActu/FicheActu.xml
WEB-INF/data/types/FicheArticle/FicheArticle.xml
WEB-INF/data/types/PageCarrefour/PageCarrefour.xml
WEB-INF/data/types/Video/Video.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/tags/titleSimple.tag
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf
plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf
plugins/SoclePlugin/types/FicheArticle/ficheArticleTechnique.jspf
plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp
plugins/SoclePlugin/types/Video/doVideoFullDisplay.jsp

Début de traitement des types de contenus impactés par le multilinguisme :
Déclaration des champs texte en multilingue
Modification des gabarits.
Initialisation du fichier en.prop (il sera à remplir avec les traductions de la DCOM)

Contenus multilingues

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/data/types/FicheActionEducative/FicheActionEducative.xml
WEB-INF/data/types/FichePublication/FichePublication.xml
WEB-INF/data/types/PortletMiseEnAvantDeContenus/PortletMiseEnAvantDeContenus.xml
plugins/SoclePlugin/jsp/templates/temoignageTemplate.jsp
plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp
plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrandsProjets.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrid.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxOneColumn.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxOneColumnHome.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxPlusRecherches.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxTemoignages.jsp

Types Magazine, Fiche action éducative, Portlet de mise en avant de contenu + gabarit témoignage

Contenus multilingues (suite)

---

WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf

Suppression de 2 styles inutilisés
Rajout de 2 styles pour les niveaux de titre

Evol styles éditeur wysiwyg (RS-1666)

---

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

Mettre un "p" quand tel / email / site seul
Mettre un "div" si plusieurs

Fix accessibilité FicheLieu (RS-1665)

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doCarouselElementCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1621

EVOL RS-1621 ajout insertion unifie CarouselElement

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

https://refonte44.atlassian.net/browse/RS-1628

FIX RS-1628 fiche aide correction label suivre demande

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/cards/doCityCard.jsp
plugins/SoclePlugin/jsp/cards/doContactCard.jsp
plugins/SoclePlugin/jsp/cards/doElectedMemberCardFull.jsp
plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheLieuCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheSAADCard.jsp
plugins/SoclePlugin/jsp/cards/doSeniorCitizensEstablishmentCard.jsp
plugins/SoclePlugin/jsp/mail/formulaireContactTemplate.jsp
plugins/SoclePlugin/types/City/doCityFullDisplay.jsp
plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp
plugins/SoclePlugin/types/EvenementInfolocale/doEvenementInfolocaleFullDisplay.jsp

Gestion du formulaire front en multilingue

Evol : form contact (RS-1651)

---

plugins/SoclePlugin/types/PortletConteneurAgenda/doPortletConteneurAgendaBoxDisplay.jsp
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp

Ajout d'un div avec une classe CSS sur le bloc recherche facettes si on se situe dans une portlet conteneur

1418 - css spécifique portlet conteneur sur recherche facette

---

plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp

Si champ EN absent, ne pas afficher la version FR.

Fix fiche publication (RS-1664)

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/mail/formulaireFaqTemplate.jsp
plugins/SoclePlugin/types/FaqAccueil/doFaqForm.jspf

Champ "code postal" en FR uniquement et champ "Pays" uniquement en EN
Petit refacto pour gestion de l'objet de mail adapté à chaque site.

Fix FAQ multilingues (RS-1662)

---

WEB-INF/data/types/AlertCG/AlertCG.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/AlertCG/doAlertCGFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1650

EVOL RS-1650 type alerte : ajout personnalisation icone

---

WEB-INF/data/types/FaqAccueil/FaqAccueil.xml
WEB-INF/data/types/FicheArticle/FicheArticle.xml
plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplayContent.jsp
plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1668

Evol rs 1668 faq affichage contact plus fiche article champ faq

---

WEB-INF/data/types/ChiffresCles/ChiffresCles.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1669

Fix+evol rs 1669 chiffre cle fix style plus ajout personnalisation icone

---

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateMenuCollapseFullDisplay.jsp

Gestion multilingues de l'affichage des catégories du menu.

Fix page carrefour (menu collapser)

---

WEB-INF/data/types/Dossier/Dossier.xml
WEB-INF/data/types/FicheActu/FicheActu.xml
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1668

EVOL RS-1668 dossier et fiche actu : ajout champ faq (contenu)

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

Traductions DCom
Même si tout n'est pas à traduire je trouve+ pratique d'avoir strictement les mêmes props de part et d'autre. + pratique pour faire des diff.

Evol : fichiers de langues

---

WEB-INF/tags/tuileContenuEnAvant.tag
plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp
plugins/SoclePlugin/types/AlertCG/doAlertCGFullDisplay.jsp
plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf

https://refonte44.atlassian.net/browse/RS-1672
N'hésitez pas à me piquer le ticket si vous voyez que j'ai loupé des choses.

EVOL RS-1672 ajout affichage anglais page d'accueil

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/ContactFormDataController.java
WEB-INF/data/types/ContactForm/ContactForm.xml
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/mail/formulaireContactTemplate.jsp
plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp

Gestion multilingue du message retour serveur (succes / erreur)

Fix form contact

---

plugins/SoclePlugin/types/CandidatureForm/doEditCandidatureForm.jsp
plugins/SoclePlugin/types/CandidatureSpontaneeForm/doEditCandidatureSpontaneeForm.jsp

Passage à "tel-national" pour être en phase sur tous les formulaires.

Fix attribut autocomplete téléphone

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/headerSection.jsp

Suppression de l'attribut "title" sur les liens du header

Fix accessibilité header (RS-1630)

---

plugins/SoclePlugin/jsp/cards/doCarouselElementCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1621

FIX RS-1621 element diaporama card : retour accessibilite alt vide

---

plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1668

FIX RS-1668 insertion FAQ : style dans dossier actu et article

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/titleBanner.tag
plugins/SoclePlugin/types/Exposition/doExpositionFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1647

EVOL RS-1647 type exposition ajout gabarit full

---

WEB-INF/data/types/ChiffresCles/ChiffresCles.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

- ajout de champs prefixe / suffixe pour chaque chiffre clé
- maj du gabarit
- remplacement id local par vrai id dans plugin.prop

Evol chiffres clés (RS-1713)

---

plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1720

EVOL RS-1720 dossier : ajout composant page utile

---

WEB-INF/data/types/PortletAgendaInfolocale/PortletAgendaInfolocale.xml
plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleFacettes.jsp

Visiblement ok pour les facettes de recherche agenda sans toucher aux gabarits

1395 - Critères secondaires recherche agenda

---

WEB-INF/data/types/FALC/FALC.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doFALCCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1719

EVOL RS-1719 renomme type FALC en Encadré avec picto + ajout champ icone

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp
plugins/SoclePlugin/jsp/cards/doFALCCardFull.jsp
plugins/SoclePlugin/types/AlertCG/doAlertCGFullDisplay.jsp

Ce sera plus propre et plus facile à maintenir comme ça.

REFACTO move code pr recuperer description category ds fct utile

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/data/types/Carousel/Carousel.xml
plugins/SoclePlugin/jsp/cards/doCarouselCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/CarouselCardFull.jspf
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2paysage&portrait+X4paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2paysage&portraitCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2paysage+X2paysage&portraitCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2paysage+X2portrait&paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2portrait&paysage+X4paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2portrait&paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX2portraitCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX3paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX3portrait&paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/CarouselCardsFull/mosaiqueX4paysageCardFull.jsp
plugins/SoclePlugin/types/Carousel/doCarouselFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-952
En principe tout les nouveaux gabarits fonctionnent, mais il y a beaucoup (trop) de duplication de code, ce qui va rendre la maintenance pénible.
Je pense qu'il est nécessaire de faire un refacto pour mettre en commun les codes dupliqués (via les tag j'imagine). C'est ce que je compte faire quand je serai de retour sur le projet.
Néanmoins comme je ne serai de retour que jeudi prochain, peut-être que Gaelle voudrait tester cette V1 fonctionnel entre temps. Ou peut-être que l'un d'entre vous voudra s'occuper du refacto avant que je revienne. Je vous laisse décider ce que vous  pensez être judicieux.
Bon courage !

Evol RS-952 creations gabarits mosaique

---

WEB-INF/data/types/ChiffresCles/ChiffresCles.xml
plugins/SoclePlugin/jsp/cards/doChiffresClesCardFull.jsp

Rajout d'un champ pour gérer le titre de l'encadré

Fix chiffres cles (RS-1713)

---

plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp

Basé sur 'tmpList' qui génère le tableau d'éléments à afficher dans la portlet carrousel

772 - "Sur le même thème" non affiché si < 3 résultats

---

plugins/SoclePlugin/jsp/portal/headerSection.jsp

- Masque le lien du header en mobile
- rajoute le lien dans le menu, en haut à gauche

FIx menu ML (RS-1641)

---

plugins/SoclePlugin/jsp/cards/doFALCCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1719

FIX RS-1719 contenu FALC enlever titre et icone par defaut

---

WEB-INF/tags/carrousel.tag
plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleFacettes.jsp

J'avais pas envie de faire un PR pour une ligne, alors j'en fais un pour deux tickets :)

1727/1729 - Fix style btn agenda + carrousel en avant accueil agenda

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/export/ExportCsvFicheArticle.java
WEB-INF/classes/fr/cg44/plugin/socle/export/ExportCsvUtils.java
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/export/exportFicheArticle.jsp
plugins/SoclePlugin/jsp/export/exportInterface.jsp
plugins/SoclePlugin/jsp/export/exportLink.jsp

Ajout d'un bouton et formulaire en BO accessible aux admins
Ajout également de méthodes utiles pour faciliter le 'copié collé' des autres contenus, et les cas où les données sont vides

1725 - Export CSV Fiche Article

---

plugins/SoclePlugin/jsp/portal/headerSection.jsp

Changement d'affichage pour l'icone ML dans le menu.
Texte sous icone dans les différentes tailles d'écran.

Fix header ML

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
plugins/SoclePlugin/jsp/cards/doFALCCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1719

FIX RS-1719 card falc variable non declare

---

WEB-INF/tags/mosaiqueImage.tag

https://refonte44.atlassian.net/browse/RS-952

FIX RS-952 style image mosaique ds wysiwyg

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

Pour activer / désactiver le partage des réseau sociaux au sein des pages.

Evol : prop éditable

---

plugins/SoclePlugin/types/Exposition/doExpositionFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1647

FIX RS-1647 full display exposition style h2 et emplacement infos libres

---

plugins/SoclePlugin/types/EvenementInfolocale/doEvenementInfolocaleFullDisplay.jsp
plugins/SoclePlugin/types/PortletAgendaInfolocale/displayResultAgenda.jsp

Finalement pas grand chose mais des soucis de configuration en lcoal ont fait durer ça trop longtemps...

1348 - btn retour recherche agenda

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/portal/archives/footerSection.jsp
plugins/SoclePlugin/jsp/portal/socialNetworksFooter.jspf

Prise en compte d'un nouvelle portlet dans le footer (si renseignee dans custom.prop)
Changement largeur colonnage
Prise en compte du centrage des textes ou non.
Rajout du tag "picture" en white list pour éditeur wysiwyg

Evol footer (RS-1705)

---

plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1720
La comparaison de code n'est pas clair, en gros j'ai déplacé les blocs de fin de page en dehors de l'élément article (comme dans le design system) et j'ai rajouté un élément section autour du bloc je m'abonne (ligne 73/75 nouveau fichier).
Modif faites car Martin avait remarqué qu'il y avait des marges horizontales trop importantes par rapport au design system.

FIX RS-1720 fiche actu marge horizontale je mabonne et sur le meme theme

---

plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf

je suis tombé dessus par hasard, petit refacto rapide

REFACTO condition affichage paragraphe ds fiche article

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/Carousel/doCarouselFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1417
je pense que le reste devrait être d'abord traité sur le design system.

FIX RS-1417 traitement points 4 à 6 du retour accessibilite

---

WEB-INF/data/types/PortletNotesAPI/PortletNotesAPI.xml
plugins/SoclePlugin/types/PortletNotesAPI/doPortletNotesAPIBoxDisplay.jsp

Proposé par sguellec
Dans l'attente des retours des plateformes API, il sera possible d'afficher une donnée en surcharge sur la portlet

Evol : surcharge notes portlet notes API

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/jsp/include/logout.jsp

Facilitera la déconnexion des contributeurs.

Evol : ajout icone déconnexion dans topbar

---

plugins/SoclePlugin/jsp/include/logout.jsp
plugins/SoclePlugin/types/PortletNotesAPI/doPortletNotesAPIBoxDisplay.jsp

Ce n'était pas le bon label qui était appelé.

Fix réseaux sociaux

---

plugins/SoclePlugin/jsp/portal/headerSection.jsp

- Déplacement d'un <div> qui n'était pas au bon endroit
- Rajout d'une classe dans le cas des sites multilingues, pour gérer l'affichage de l'icone "anglais" du menu.

Fix header (RS-1715)

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/export/ExportCsvPageUtileForm.java
plugins/SoclePlugin/jsp/export/exportInterface.jsp
plugins/SoclePlugin/jsp/export/exportPageUtileForm.jsp

https://refonte44.atlassian.net/browse/RS-1685

EVOL RS-1685 ajout export form page utile

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/properties/plugin.prop

https://refonte44.atlassian.net/browse/RS-1685

FIX RS-1685 export page utile form retours fonctionnels

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop

Rajout d'attribut en whitelist.

FIX RS-1703 conf wysiwyg

---

plugins/SoclePlugin/jsp/portal/socialNetworksShare.jspf

https://refonte44.atlassian.net/browse/RS-1720

FIX RS-1720 Dossier pb de marge avec partage reseaux sociaux

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/cards/doExpositionCardFull.jsp

https://refonte44.atlassian.net/browse/RS-1647

FIX RS-1647 exposition ajout insertion wysiwyg

---

WEB-INF/classes/fr/cg44/plugin/socle/VideoUtils.java
plugins/SoclePlugin/jsp/portal/socialNetworksShare.jspf

Mon PR précédent était complètement faux. Celui-ci rétabli les choses.

Fix commit Réseau Sociaux + Revert VideoUtils

---

plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp
plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1668

FIX RS-1668 largeur FAQ ds article et actu

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX3portrait1paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX3portraitFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1771

Fix RS-1771 gabarits mosaiques

---

WEB-INF/data/types/FaqAccueil/FaqAccueil.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/posezUneQuestion.jsp

https://refonte44.atlassian.net/browse/RS-1791
+ petit refacto avec le title "Fermer l'aide : Vous avez une question ?" qui était en dur (ligne 33 et 38)

EVOL RS-1791 faq ajout champ libelle pour le bouton overlay

---

plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1792

Evol RS-1792 fiche emploi ajout partage reseaux sociaux

---

WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/tableauDeBord/tableauDeBordPageUtileForm.jsp
plugins/SoclePlugin/jsp/tableauDeBord/tableauDeBordPageUtileFormLink.jsp

https://refonte44.atlassian.net/browse/RS-1085
Dans l'optique que c'est toujours un work in progress, j'ai laissé le css perso et le code java dans la jsp. Mais in fine, ce sera à externaliser ou à remplacer par du code/style déjà existant.
Bon courage à qui prendra la suite du ticket (si je ne reviens pas la semaine prochaine) !

EVOL RS-1085 ajout tableau de bord page utile

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/export/ExportCsvUtils.java
WEB-INF/data/types/FicheArticle/FicheArticle.xml

A MERGE APRES https://github.com/departement-loire-atlantique/jPlatformSocle/pull/995 (dépendance sur cette branche)

1687 - retour export fiche aide

---

WEB-INF/classes/fr/cg44/plugin/socle/export/ExportCsvUtils.java
plugins/SoclePlugin/types/PortletFacetteAgendaTarif/doPortletFacetteAgendaTarifBoxDisplay.jsp

A MERGE APRES https://github.com/departement-loire-atlantique/jPlatformSocle/pull/997 (3e dans la liste de dépendances !)

1697 - fix label mme contact

---

WEB-INF/data/types/Exposition/Exposition.xml
plugins/SoclePlugin/jsp/cards/doExpositionCardFull.jsp
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusExpositions.jsp
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1647

FIX RS-1647 liste contenu add gabarit expo + exposition add image carree

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/titleSimple.tag

Evol du tag "titleSimple"+ ajout de méthode utilitaire + ajout de labels qui serviront sur le site Observatoire.

Evol init observatoire

---

WEB-INF/classes/fr/cg44/plugin/socle/export/ExportCsvUtils.java

Récupération de correctifs manquants lors de merges de PR effectués dans le mauvais ordre.
La prochaine fois je regarderai pour tout mettre en un seul PR

Fix merges export CSV

---

plugins/SoclePlugin/types/AccueilDelegation/doAccueilDelegationFullDisplay.jsp
plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp
plugins/SoclePlugin/types/PortletPush/doPortletPushBoxDisplay.jsp

Va avec la correction en recette du design-system : RS-1318 : Correction largeur Portlet Push et la branch 'RS-1720'

RS-1318 : Correction largeur portlet Push

---

WEB-INF/classes/fr/cg44/plugin/socle/export/ExportCsvPageUtileForm.java
plugins/SoclePlugin/jsp/tableauDeBord/tableauDeBordPageUtileForm.jsp

https://refonte44.atlassian.net/browse/RS-1685

FIX RS-1685 export page utile retournait que 10 derniers elements

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/portal/headerSection.jsp

Refacto des prop (certaines n'étaient jamais utilisées)
MAJ picto drapeau du menu (le drapeau FR n'était pas pris en compte)

Fix header + menu multilingue

---

WEB-INF/data/types/Exposition/Exposition.xml
plugins/SoclePlugin/types/Exposition/doExpositionFullDisplay.jsp

Rajout indication taille image principale
Style bouton large pour la réservation.

Evol fiche expo (RS-1647)

---

plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrandsProjets.jsp

Prise en compte du nb max d'éléments de la portelt RI.
Fix sur nb éléments de la 2è colonne.

fix portlet "grands projets" (RS-1826)

---

plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplayContent.jsp

1825 - réfacto fix ordre faq

---

plugins/SoclePlugin/types/Carousel/doCarouselFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1417

EVOL RS-1417 ajout titre et sous titre dans Diaporama

---

plugins/SoclePlugin/jsp/tableauDeBord/tableauDeBordPageUtileForm.jsp
plugins/SoclePlugin/jsp/tableauDeBord/tableauDeBordPageUtileFormPublication.jsp

https://refonte44.atlassian.net/browse/RS-1085

EVOL RS-1085 ajout page dedie aux avis d'une publication

---

plugins/SoclePlugin/types/Carousel/doCarouselFullDisplay.jsp

https://refonte44.atlassian.net/browse/RS-1747

FIX RS-1747 retours accessibilite diaporama

---

plugins/SoclePlugin/types/Exposition/doExpositionFullDisplay.jsp

Ouverture en target Blank du lien de reservation.

evol fiche exposition (RS-1837)

---

WEB-INF/data/types/Canton/Canton.xml
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
WEB-INF/tags/titleNoImage.tag
plugins/SoclePlugin/jsp/cards/doChiffresClesCardGreen.jsp
plugins/SoclePlugin/jsp/portal/socialNetworksShare.jspf
plugins/SoclePlugin/types/Canton/doCantonFullDisplay.jsp

N'inclut pas la partie "carte"

1805 - Evolution graphique canton

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/sitesEtApplis.jspf

Gestion des sites et applis "en dur" et plus en utilisant des catégories et des portlets redirection.
Les thématiques et sites sont gérés en JSP + en propriétés.

Evol Sites et Applis (RS-735)

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusFullDisplay.jsp
plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusVideos.jsp
plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp

- Insertion de multiples vidéos via type de contenu "ListeDeContenus"
- Suppression d'id inutile sur h3

Evol : gabarit de vidéo pour type ListeDeContenus (RS-1827)

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/sitesEtApplis.jspf

Fix Sites et Applis (RS-735)

---

plugins/SoclePlugin/jsp/include/mosaiqueCommons.jspf
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2paysage1portraitFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2paysage1portraitPlusX4paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2paysagePlusX2paysage1portraitFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2paysagePlusX2portrait1paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2portrait1paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2portrait1paysagePlusX4paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX2portraitFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX3paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX3portrait1paysageFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselMosaiqueX3portraitFullDisplay.jsp

Avec en prime un fichier commons

1417 - titre et sous titre mosaiques

---

WEB-INF/data/types/FicheAide/FicheAide.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

Autorise également plus d'un type de contenu pour le champ "qui contacter" -> plus précisément pour pouvoir utiliser le contenu "Contact".

1842 - Suppr modales fiche aide

---

plugins/SoclePlugin/jsp/cards/doCarouselCardFull.jsp

Le media card pour diapo doit afficher uniquement le gabarit query.simple

1417 - template forcé pour media carousel

---

WEB-INF/data/types/PortletFilTwitter/PortletFilTwitter.xml

hotfix  : portlet fil twitter

---

WEB-INF/classes/fr/cg44/plugin/socle/twitter/EmojiTwitter.java

Oubli de classe dans le plugin

hotfix : classe pour fil Twitter

---

plugins/SoclePlugin/types/PageCarrefour/doPageCarrefourFullDisplay.jsp

Semble être un cas particulier

1834 - padding top sur portlet FAQ dans page carrefour

---

plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

Ajout d'une ligne incorrectement intégrée au commit précédent

1854 - fix règle intro faire demande fiche aide

---

plugins/SoclePlugin/types/ContenuPush/doContenuPushHorizontalCard.jspf
plugins/SoclePlugin/types/PortletPush/doPortletPushBoxDisplay.jsp

Lignes restaurées pour le bon DOM

1318 - fix superposition portlet push

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateMenuCollapseHideEmptyChildrenFullDisplay.jsp

Pour portlet utilisée sur les pages carrefour.
N'affiche pas les catégories si pas de contenus dedans.

Evol : nouveau gabarit de nav

---

jcore/doEmptyHeader.jspf

1859 - ExtraData ou DBData titre SEO selon contenu

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/types/EvenementInfolocale/doEvenementInfolocaleFullDisplay.jsp

Ne pas mettre d'espace avant le caractère " : " en version anglaise.
Pour la suite il faudra penser à utiliser la prop "jcmsplugin.socle.deux-points" dans les JSP car les règles typographiques sont différentes en français et anglais.

1876 : fix ponctuation

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/rgpd/orejimeConfig.jsp

Seules les 2 textes de description présent sur la modale sont éditables.
Les autres libellés passent en prop de langues.

1757 evol : multilingue pour modale Orejime

---

WEB-INF/data/types/Webdoc/Webdoc-templates.xml
WEB-INF/data/types/Webdoc/Webdoc.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/webdocPortal.jsp
plugins/SoclePlugin/jsp/tableauDeBord/tableauDeBordPageUtileForm.jsp
plugins/SoclePlugin/types/Webdoc/doWebdocFullDisplay.jsp

Accessibilité difficile à mettre en place (impossible de modifier l'HTML d'un iframe depuis l'extérieur, sauf cas contraire que je n'aurais pas en tête)
Le bandeau de l'iframe est caché sous le bandeau custom pour avoir le comportement lien retour custom demandé par le ticket.
C'est un peu 'bricolage' mais si vous avez de meilleures suggestions...

1866 - intégration webdocs

---

jcore/doEmptyHeader.jspf

Utilisation du nouveau champ "Meta description" (module SEO) si celui-ci a été renseigné.

Evol  : meta description

---

plugins/SoclePlugin/types/CandidatureSpontaneeForm/editFormCandidatureSpontaneeForm.jsp
plugins/SoclePlugin/types/PageUtileForm/doEditPageUtileForm.jsp

Classe CSS en target pour le comportement JS censé bloquer le bouton de soumission et éviter les double soumissions.
OK en local. En attente de màj sur le dev-ds (ne sera pas mergé avant ce test)

1919 - Refacto JS btn soumission

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/types/PortletQueryForeach/doPortletQueryForeachListeSimple.jsp

Génération d'une liste simple ul/li avec titre du contenu et lien vers ce contenu.
Servira pour Numérique mais potentiellement ailleurs d'où la présence dans Socle.

Evol : nouveau gabarit PQF

---

jcore/doEmptyHeader.jspf

Pour éviter les titres "X résultats recherche facette" sur les pages de contenus

1862 - Titre SEO tuile linkedin / twitter

---

WEB-INF/tags/titleSimple.tag
plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp
plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

Divers correctifs liés à un audit de plusieurs pages.

Fix accessibilité w3c (RS-1926)

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/tags/articleVideo.tag
plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp

RÀF : bug de scroll JS qui bloque en haut de page

731 - chapitrage vidéo + màj depuis design system

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java

Passage de Util.isEmpty vers le nécessaire et utile json.isNull pour éviter des erreurs dans le log.
Ajout de la condition à tous les champs repérés faute du manque d'information sur les champs obligatoires / optionels

Refacto securite champs agenda

---

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/InscriptionPressFormDataController.java
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/mail/formulaireEspacePresseDemandeConfirmationInscriptionTemplate.jsp
plugins/SoclePlugin/jsp/mail/formulaireEspacePresseNotificationInscriptionTemplate.jsp
plugins/SoclePlugin/jsp/portal/inscription/valideInscriptionEspacePresse.jsp
plugins/SoclePlugin/types/InscriptionPressForm/doEditInscriptionPressForm.jsp
plugins/SoclePlugin/types/InscriptionPressForm/editFormInscriptionPressForm.jsp

- choix du password pour l'utilisateur
- modifs de gabarits de mails
- mail de notification au pôle presse après création membre

Fix inscription espace presse

---

WEB-INF/data/types/Lien/Lien.xml
plugins/SoclePlugin/jsp/templates/plusRecherche.jsp
plugins/SoclePlugin/jsp/templates/plusRechercheLien.jspf
plugins/SoclePlugin/jsp/templates/tuileCommon.jsp
plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp
plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGridIcon.jsp

Fix accessibilite (RS-1875)

---

WEB-INF/classes/fr/cg44/plugin/socle/importation/ImportLienFromCsv.java
WEB-INF/data/types/Lien/Lien.xml
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/import/importLienInterface.jsp

Importe le contenu d'un fichier CSV pour générer des liens dans un workspace spécifique.
Code jetable car très spécifique dans le nombre de colonne et la correspondance des champs à alimenter.
Ajout d'un champ "Classement" pour le type "Lien"

feat : import de liens

---

WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf

Ajout du style "exposant" dans l'éditeur.
La CSS sera sans doutes à revoir car en pratique le texte se met + bas au lieu d'être + haut... A valider avec MOA.

evol : Tiny MCE (RS-1982)

---

WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/InscriptionPressFormDataController.java
plugins/SoclePlugin/types/InscriptionPressForm/doEditInscriptionPressForm.jsp
plugins/SoclePlugin/types/InscriptionPressForm/editFormInscriptionPressForm.jsp

Pas sûr de pourquoi editFormInscriptionPressForm.jsp  a été modifié mais le voilà

1980 - Chp média obligatoire form inscription presse

---

WEB-INF/data/types/CarouselElement/CarouselElement.xml
WEB-INF/tags/figurePicture.tag
WEB-INF/tags/mosaiqueImage.tag
plugins/SoclePlugin/jsp/cards/doCarouselElementCardFull.jsp
plugins/SoclePlugin/jsp/include/elementCarouselLinkCommons.jspf
plugins/SoclePlugin/types/Carousel/doCarouselFullDisplay.jsp
plugins/SoclePlugin/types/Carousel/doCarouselSwiperOneBlocFullDisplay.jsp
plugins/SoclePlugin/types/PortletCarrouselDimagesHome/doPortletCarrouselDimagesHomeBoxDisplay.jsp

Création d'un draft - modifications potentielles après retour accessibilité

1978 - liens elem diapo

---

WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/jsp/portal/archives/footerSection.jsp
plugins/SoclePlugin/jsp/portal/footerSection.jsp
plugins/SoclePlugin/jsp/portal/handicap/footerSection.jsp
plugins/SoclePlugin/jsp/portal/numerique/footerSection.jsp
plugins/SoclePlugin/jsp/portal/observatoire/footerSection.jsp

Besoin créé sur le site aidants, où le logo du footer doit correspondre à son logo propre

Update : URL logo footer paramétrable

---

plugins/SoclePlugin/jsp/portal/aidants/footerSection.jsp

Correspondance avec la maquette (le bloc RS m'a échappé)

Update footer aidants - mise en page

---

WEB-INF/plugins/SoclePlugin/plugin.xml
plugins/SoclePlugin/jsp/portal/blocMenuRecherche.jspf
plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesHeader.jsp

Possibilité d'utiliser une portlet recherche facettes en header. Configuration identique à une portlet recherche facette classique.

2023 - gabarit recherche facette en header

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/RequestManager.java

Boucle infinie corrigée suite à une erreur 503 rencontrée chez l'API infolocale

Refacto request manager sur refreshToken

---

plugins/SoclePlugin/jsp/scripts/listCMYKPictures.jsp

En étant connecté, lancer le script sur l'URL jcms/plugins/SoclePlugin/jsp/scripts/listCMYKPictures.jsp

Script de détection des images incompatibles

---

WEB-INF/classes/fr/cg44/plugin/socle/ApiUtil.java

Fix appels API

---

jcore/doEmptyHeader.jspf

Pour exploitation JS (moteurs à facettes)

evol : rajout du nom du site dans le DOM (RS-1936)

---

plugins/SoclePlugin/types/FaqAccueil/doFaqForm.jspf

Apparaît quand on clique sur une catégorie et qu'un contenu n'est pas chargé

2043 - fix NPE sur doFaqForm

---

WEB-INF/data/types/FicheAide/FicheAide.xml
plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp

Pour la double parenthèses je ne sais pas d'où elle sort !

2035 - fix fiche aide / position champs SEO

---

plugins/SoclePlugin/jsp/templates/fileDocumentEmbedTemplate.jsp
plugins/SoclePlugin/types/FileDocument/doFileDocumentEmbedDisplay.jsp

Casse en preprod, apparaît en local après nettoyage du cache

2050 - fix path include

---

WEB-INF/classes/fr/cg44/plugin/socle/mailjet/MailjetManager.java

Ajout de la récupération d'une liste de campagnes.

Mailjet campaigns

---

plugins/SoclePlugin/jsp/cards/doCantonCard.jsp
plugins/SoclePlugin/jsp/cards/doCantonCardFull.jsp
plugins/SoclePlugin/jsp/cards/doCityCard.jsp
plugins/SoclePlugin/jsp/cards/doDossierCard.jsp
plugins/SoclePlugin/jsp/cards/doElectedMemberCard.jsp
plugins/SoclePlugin/jsp/cards/doElectedMemberCardFull.jsp
plugins/SoclePlugin/jsp/cards/doEvenementInfolocaleCard.jsp
plugins/SoclePlugin/jsp/cards/doEvenementInfolocaleMarker.jsp
plugins/SoclePlugin/jsp/cards/doEvenementInfolocaleVerticalCard.jsp
plugins/SoclePlugin/jsp/cards/doEvenementInfolocaleVerticalCardCarrousel.jsp
plugins/SoclePlugin/jsp/cards/doFicheActionEducativeCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheAideCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheArticleCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheEmploiStageCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheEquipementCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheLieuCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheLieuResultCard.jsp
plugins/SoclePlugin/jsp/cards/doFicheSAADCard.jsp
plugins/SoclePlugin/jsp/cards/doLienCard.jsp
plugins/SoclePlugin/jsp/cards/doPressCommuniqueCard.jsp
plugins/SoclePlugin/jsp/cards/doSeniorCitizensEstablishmentCard.jsp
plugins/SoclePlugin/jsp/cards/doSpectacleCard.jsp
plugins/SoclePlugin/jsp/templates/doFichePublicationTuileHorizontaleGrey.jsp
plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp
plugins/SoclePlugin/jsp/templates/tuileHorizontaleGrey.jsp
plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp

Aussi sur Archives et Inforoutes

2060 - accessibilité p avec lien

---

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleMetadataUtils.java
WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/include/doMetadataEventInfolocale.jspf

Plus de clarté et suppression de caractères inutiles.

Evol display horaires infolocale

---

plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp

Une simple inversion de labels

1935 - libellé lire journal en ligne accessibilité

---

plugins/SoclePlugin/types/EvenementInfolocale/doEvenementInfolocaleFullDisplay.jsp

Style chapo mais sans gras pour le champ "texte long"

Fix style evenementInfolocale full (2066)

---

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/headerSection.jsp

Pas de lien si on est sur la page d'accueil
Petite modif de label pour le ALT
Rajout d'une balise P pour encadrer l'image. Vu avec Franck L.

Fix accessibilité logo header (1925)

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
plugins/SoclePlugin/jsp/portal/sitesEtApplis.jspf

MAJ de la liste de sites et applis du DEP.
3 suppressions, 1 MAJ
Note : cette fonction "sites et applis" n'a jamais été traduite en anglais, et fera l'objet d'un ticket ultérieurement.

Evol : site et applis

---

WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/FicheLieuDataController.java
WEB-INF/data/types/FicheLieu/FicheLieu.xml
WEB-INF/plugins/SoclePlugin/plugin.xml
WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
WEB-INF/plugins/SoclePlugin/properties/plugin.prop
plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp

Comportement BO sur les fichiers ASU associés + display conditionnel du bloc ASU en FO
Ce PR ne contient pas la partie "mire d'authentification"

2110 - fiche lieu bloc réservé ASU

---

plugins/SoclePlugin/jsp/portal/aidants/footerSection.jsp

Fix : permuter les logos "dep" et "aidant"

---

plugins/SoclePlugin/types/FicheEquipement/doFicheEquipementFullDisplay.jsp

Ne pas indexer ce type de contenu

Fix : SEO fiche équipement (RS-2129)

---

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java

Extraction du jour/mois/année à partir d'une date texte. utilisé pour valuer les champs dates sur Assmat.

Evol : fonctions de date

---

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop
WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop

Utilisés pour les champs MDP sur la page http://design.loire-atlantique.fr/components/form.html

Labels display champ

---

WEB-INF/classes/fr/cg44/plugin/socle/channellistener/SocleChannelListener.java
plugins/SoclePlugin/types/ContenuPush/doContenuPushVerticalCard.jspf

Supprimer le type button sur les "a"

Fix : a11y Push

---

WEB-INF/data/types/FicheLieu/FicheLieu.xml
plugins/SoclePlugin/jsp/reprise/repriseFicheLieu.jsp

- Rajout du chap "ID SOLIS"
- Fix id catégorie en dur
- Adaptation moulinette import

Evol : reprise fiches lieu (AS-147)
