WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/FicheArticleDataController.java, WEB-INF/plugins/SoclePlugin/plugin.xml
Le comportement actuel est de forcer la complétion du champ "Contenu paragraphe" sur un type simple, et d'au moins un des champs "Contenu paragraphe de l'onglet" sur un type onglet.
=> Evol : Initialisation du DataController pour la Fiche Article

plugins/SoclePlugin/jsp/portal/headerSection.jsp
Les niveaux 1 du menu doivent pouvoir renvoyer directement vers un contenu (s'il est catégorisé en tant que "contenu principal")
=> Evol : liens sur niveau 1 du menu

plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf, plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf
Ajout de la balise <jalios:wysiwyg> autour des champs wysiwyg sinon les liens internes (<jalios:datalink>) ne sont pas interprétés.
=> Fix wysiwyg FicheArticle et FicheActu

WEB-INF/data/types/ListeDeContenus/ListeDeContenus.xml, WEB-INF/data/types/Video/Video.xml, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/tags/titleSimple.tag, plugins/SoclePlugin/types/FicheAide/doFicheAideEncadre.jspf, plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf, plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusDocuments.jsp, plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp
Si une vidéo est présente, alors elle doit remplacer l'image, dans la zone de titre.
=> Intégration des vidéo dans les fiches article

WEB-INF/data/types/Lien/Lien.xml, WEB-INF/data/types/PortletMiseEnAvantDeContenus/PortletMiseEnAvantDeContenus.xml, plugins/SoclePlugin/jsp/templates/tuileCommon.jsp, plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrandsProjets.jsp
Rajout de la gestion des liens internes sur le bouton dans la portlet "Mise en avant de contenus" + renommage champ lien externe
Gestion du lien du bouton dans le gabarit
Refacto suite renommage champ.
=> Fix RS-780 bloc "grands projets"

WEB-INF/plugins/SoclePlugin/properties/plugin.prop, WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf, WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-styles.conf
J'ai ajouté le code dans le fichier : configuration-styles.conf
A voir si faire un autre fichier ou renommer celui-ci qui ne gère plus seulement le style mais aussi les balises autorisées.
Ce code ne peut fonctionner qu'après la correction du bug Jalios : https://community.jalios.com/jcms/jc1_543054/fr/wysiwyg-extended-valid-elements-de-tinymce-ne-marche-pas-sur-jalios
=> Wysiwyg balise script

WEB-INF/tags/titleSimple.tag, plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/commonTitreArticleActu.jspf, plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf, plugins/SoclePlugin/types/Video/doVideoFullDisplay.jsp
Mise en commun du code d'affichage du titre.
Refacto du tag "titleSimple" pour l'alléger. On lui passe en param l'objet Video plutot que les différents champs necessaires à l'affichage.
=> Fix titre image/vidéo sur FicheArticle / FicheActu / Video

WEB-INF/data/types/PortletCarousel/PortletCarousel.xml, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/templates/tuileCommon.jsp, plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp, plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusTuileHorizontale.jsp, plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf, plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrandsProjets.jsp, plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrid.jsp, plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxOneColumn.jsp
Finalement, utilisation de media-template plutôt que le tag "tuileVerticale.tag", dans un soucis d'uniformisation, notamment p/r aux tuiles de résultats de recherche.
Renommage des media-template : quand la tuile est "dark" c'est qu'elle est dans un contexte "clair" et inversement.
=> Refacto des tuiles Carrousel

plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp
retours de ce ticket
https://refonte44.atlassian.net/browse/RS-914
Je ne suis pas sûr de comprendre par ce qu'elle entend par "Les listes de contenus de type lieu", ou plutôt en quoi c'est différent avec "Le liens contenus intégrés vers une fiche lieu"
Si tu pouvais m'éclairer @sguellec, ça serait cool.
=> FIX utilise adresse ecrire au lieu adresse simple

plugins/SoclePlugin/types/FicheAide/doFicheAideEncadre.jspf, plugins/SoclePlugin/types/FicheArticle/doFicheArticleEncadre.jspf
Commentaire JAVA plutôt que HTML : il y avait des caractère mal encodés dans le source et ça ne plaisait pas au validateur W3C. Du coup j'ai rajouté l'encodage UTF8.
=> Refacto (mini) encadrés Fiche Aide

plugins/SoclePlugin/jsp/portlet/portletFacetteAutoCompletion.jspf, plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteMotcle/doPortletFacetteMotcleBoxDisplay.jsp
Sous les label de formulaire pour coller au DS.
Note : certains formulaires étaient déjà en span ce qui explique que peu de fichiers sont impactés.
=> Refacto champs de formulaires : remplacement des div en span

WEB-INF/plugins/SoclePlugin/plugin.xml, WEB-INF/tags/categoryList.tag, WEB-INF/tags/categoryTree.tag, WEB-INF/tags/tooltip.tag, plugins/SoclePlugin/types/FicheSAAD/doFicheSAADFullDisplay.jsp, plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateMenuCollapseFullDisplay.jsp
- création du tag "tooltip"
- mise en place pour les catégories de la fiche SAAD
- refacto : renommage du tag categoryList.tag en categoryTree.tag
- le tag categoryList.tag affiche désormais une liste de catégories avec séparateur et la possibilité d'afficher une infobulle.
=> Fix fiche SAAD : ajout d'infobulles

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/types/FicheLieu/doFicheLieuEmbedDisplayContent.jsp
Renommage de la méthode.
Cette méthode regarde juste si la publication a été mise dans la catégorie de classement "Contenu non répertorié".
Ca m'a servi pour les tuile de contacts et servira pour le moteur de recherche.
=> Evol : contenu non répertorié

WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/portal/headerSection.jsp
Si présence d'une propriété avec un logo mobile alors on génère les 2 balise <source> dans la balise <picture> utilisée pour l'affichage du logo.
Si absent alors on génère uniquement la balise <img>.
Dans le cas du site handicap la propriété sera mise directement dans le custom.prop
=> Fix header : gestion d'un logo mobile / desktop

plugins/SoclePlugin/types/PageCarrefour/doPageCarrefourFullDisplay.jsp
Les encadré peuvent être soit des portlets, soit directement des contenus.
Modification de l'inclusion en fonction du type.
=> Fix encadrés page carrefour

WEB-INF/data/types/FicheArticle/FicheArticle.xml, plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf, plugins/SoclePlugin/types/FicheArticle/ficheArticleTechnique.jspf
Ajout de champs pour préparer la reprise des "articles géolocalisés"
Ajout d'un champ caché portlets encadrés pour gabarit "technique" (article simple + colonne droite qui sera utilisé pourles formulaires de contacts par exemple).
Le gabarit "technique"
=> Evol fiche article

plugins/SoclePlugin/types/FicheActu/doFicheActuFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/ficheArticleSimple.jspf
Fiche actu : finalement ne pas afficher un titre seul s'il n'a pas de paragraphe associé
Correctif d'un bug : si titre seul suivi d'un couple titre/paragraphe, le titre apparaissait.
=> Fix gestion des titres de paragraphes

WEB-INF/data/types/PageCarrefour/PageCarrefour.xml
Ajout d'un champ "titre URL" pour mettre dans l'URL à la place du champ "titre".
Champ pris en compte par le module SEO
=> Evol page carrefour SEO

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java, WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java, WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/ContactFormDataController.java, WEB-INF/data/types/ContactForm/ContactForm.xml, WEB-INF/plugins/SoclePlugin/plugin.xml, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, WEB-INF/tags/message.tag, plugins/SoclePlugin/jsp/doMessageBoxCustom.jspf, plugins/SoclePlugin/jsp/forms/doFormDecodeParams.jsp, plugins/SoclePlugin/jsp/forms/doFormFooter.jspf, plugins/SoclePlugin/jsp/forms/doFormHeader.jspf, plugins/SoclePlugin/jsp/mail/formulaireContactTemplate.jsp, plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp, plugins/SoclePlugin/types/ContactForm/editFormContactForm.jsp
- Déclaration du type de formulaire
- Gabarits de saisie personnalisés
- Copie de doMessageBox.jspf pour adapter au DS
- Ajout d'un tag pour gestion des messages succes/erreur pour remplacer le natif <jalios:message>
- Datacontroller pour vérifier saisie + envoi de mail
- Ajout d'une méthode dans SocleUtils pour parser et transmettre les paramètres du formulaire.
- Ajout de classe utilitaire d'envoi de mail
=> Evol : intégration du formulaire de contact

WEB-INF/plugins/SoclePlugin/properties/plugin.prop
Ajout d'une propriété pour avoir une classe spécifique sur le logo du header.
Sera utilisé pour handicap. La gestion du style est déjà présente mais il manquait la propriété.
=> Fix : gestion du logo du header

plugins/SoclePlugin/types/Dossier/doDossierFullDisplay.jsp
Si un titre de paragraphe est manquant, ça affichait "null" dans le sommaire.
=> Fix sommaire dossier

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java
Passé d'une liste de 7 jours à un duo date début / date fin, ce qui sera plus pratique à lire pour infolocale
=> Refacto : modification de la valeur retournée pour les 7 prochains jours

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/EvenementContent.java, WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java, WEB-INF/classes/fr/cg44/plugin/socle/infolocale/RequestManager.java, WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java, plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleBoxDisplay.jsp
Les mettre en place dès la génération des événements plutôt que de piocher dans le flux json
=> Refacto : récupération et enregistrement des metadatas infolocale

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/forms/doFormFooter.jspf, plugins/SoclePlugin/types/CandidatureSpontaneeForm/doEditCandidatureSpontaneeForm.jsp, plugins/SoclePlugin/types/CandidatureSpontaneeForm/editFormCandidatureSpontaneeForm.jsp, plugins/SoclePlugin/types/ContactForm/editFormContactForm.jsp, plugins/SoclePlugin/types/FicheArticle/ficheArticleTechnique.jspf
- Modif du libellé du titre pour la candidature spontanée
- Prise en compte du champs image dans l'article embarquant le formulaire
- Suppressions des propriétés RGPD dans les fichiers de prop
- Mentions RGPD dans portlets Wysiwyg rendues paramétrables
=> Fix formulaires

WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/cards/doContactCard.jsp, plugins/SoclePlugin/jsp/cards/doElectedMemberCardFull.jsp, plugins/SoclePlugin/jsp/templates/doFichePublicationTuileHorizontaleGrey.jsp
Rajout de déclaration de gabarits pour l'insertion d'élu, de contact et de fiche publication dans les zones wysiwyg.
Réutilisation des gabarits de tuiles du moteur à facettes avec modif des gabarits pour gérer l'affichage de la tuile sur la moitié de son conteneur.
=> Evol : insertion unifiée (RS-1247, RS-1280, RS-1281)

WEB-INF/tags/titleSimple.tag
Appliquer la taille "image principale" et pas "image bandeau"
=> Fix : taille image pour titre simple

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java, plugins/SoclePlugin/jsp/cards/doEvenementInfolocaleVerticalCard.jsp
Le comparateur n'aimait pas qu'on lance un "compareTo" sur des sous-éléments d'objets qui peuvent être identiques. Au final j'ai dû faire l'action 'à la main' plutôt que d'utiliser le natif, pour le même résultat...
=> Quickfix : anomalie tri agenda + tuile verticale agenda

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleBoxDisplay.jsp
Le second point est là car Infolocale utilise deux formats : dd-MM-yyyy quand on doit faire une recherche avec des paramètres de date, et yyyy-MM-dd sur les dates des événements reçus...
=> Fix sur l'ordre des événements - séparation des deux patterns dates infolocale

WEB-INF/plugins/SoclePlugin/plugin.xml, plugins/SoclePlugin/jsp/reprise/contenusSansGeolocLink.jsp
Pour faciliter accès à la page listant les contenus sans géolocalisation.
=> Evol : ajout d'un lien vers JSP dans espace d'admin

plugins/SoclePlugin/types/AccueilAnnuaireAgenda/doAccueilAnnuaireAgenda_Annuaire.jsp, plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/ficheArticleOnglets.jspf, plugins/SoclePlugin/types/PageCarrefour/doPageCarrefourFullDisplay.jsp, plugins/SoclePlugin/types/WelcomeSection/doWelcomeSectionFullDisplay.jsp
Certaines tuile ont une largeur de 50% quand intégrée dans un wysiwyg en partie centrale.
Si ces tuiles sont intégrées en colonne de droite il faut alors qu'elles s'affichent en 100% et pas 50%.
L'ajout d'une classe sur la balise <aside> permet cela.
=> Fix : affichage de tuiles en colonne droite (RS-1280)

plugins/SoclePlugin/jsp/facettes/commonParamsFacettes.jspf, plugins/SoclePlugin/types/PortletFacetteAdresse/doPortletFacetteAdresseBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteAgendaAccessibilit/doPortletFacetteAgendaAccessibilitBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteAgendaCommune/doPortletFacetteAgendaCommuneBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteAgendaDate/doPortletFacetteAgendaDateBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteCanton/doPortletFacetteCantonBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteCommune/doPortletFacetteCommuneBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteCommuneAdresseLiee/doPortletFacetteCommuneAdresseLieeBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletFacetteDelegationBoxDisplay.jsp, plugins/SoclePlugin/types/PortletFacetteDelegation/doPortletSearchPdcv.jsp, plugins/SoclePlugin/types/PortletFacetteTitre/doPortletFacetteTitreBoxDisplay.jsp
Voir page DS http://dev-design.loire-atlantique.fr/templates/page-resultats-recherche.html
=> Fix : sur le portail de recherche facette, les champs doivent être en standard

plugins/SoclePlugin/jsp/forms/checkPageUtile.jsp, plugins/SoclePlugin/jsp/mail/formulairePageUtileTemplate.jsp, plugins/SoclePlugin/types/AccueilDelegation/doAccueilDelegationFullDisplay.jsp, plugins/SoclePlugin/types/Canton/doCantonFullDisplay.jsp, plugins/SoclePlugin/types/City/doCityFullDisplay.jsp, plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp, plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp, plugins/SoclePlugin/types/FicheArticle/doFicheArticleFullDisplay.jsp, plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp, plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp, plugins/SoclePlugin/types/FicheSAAD/doFicheSAADFullDisplay.jsp, plugins/SoclePlugin/types/PageUtileForm/editFormPageUtileForm.jsp, plugins/SoclePlugin/types/SeniorCitizensEstablishment/doSeniorCitizensEstablishmentFullDisplay.jsp
Changement de règle sur contrôle de saisie du formulaire.
Ajout d'une règle d'affichage pour ne pas afficher le bloc "page utile" quand on est en résultat de recherche latérale du moteur à facettes.
=> Fix page utile

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java
Les retours chariots "\r\n" ou "\n" ne sont pas bien interprétés par Outlook.
Je repasse sur le fonctionnement précédent, à savoir génération des saut de ligne en HTML puis conversion via méthode utilitaire Jalios.
Attention, la méthode en question est dépréciée, mais je voudrais voir si ça fonctionne.
On rétabli en fait le fonctionnement de l'ancien site.
=> fix mail candidature

WEB-INF/classes/fr/cg44/plugin/socle/queryfilter/IgnoreQueryFilter.java
Rajout d'un test car le "context" est null lors d'un appel à l'Open Api, viales URLs de type "/rest/search"
=> Fix sur le "IgnoreQueryFilter"

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateBreadcrumb.jsp
Désactiver le fil d'ariane lors de l'affichage en gabarit "full" en mode latéral du résultat de recherche à facettes (il peut générer une exception).
=> Hotfix affichage fil ariane  (RS-1456)

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp
Ajout de la réécriture d'url pour permettre à Xavier de tester et de finir son JS sur le sujet. Par défaut la réécriture est à false. L'ancien paramètre "jcmsplugin.socle.url-rewriting.disabled"  et le nouveau "jcmsplugin.socle.url-rewriting" cohabitent tant que le développement n'est pas finalisé.
=> Ajout de l'attribut de réécriture d'url pour tester le js

WEB-INF/classes/fr/cg44/plugin/socle/policyfilter/WysiwygPolicyFilter.java
supprimer les <p> vides de type <p>&nbsp;</p>
supprimer les&nbsp;&nbsp;multiples pour n'en garder qu'un seul
supprimer les title=""
supprimer les aria-label=""
supprimer les doubles<br> de type <br><br> et les remplacer par <br>
=> 1021 - màj accessibilité wysiwyg

plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateBreadcrumb.jsp
pas de ticket lie
niveau affichage, on obtient à la place de l'exception :
[icone de maison] / racine
=> FIX fil ariane array out of bound exception

plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp, plugins/SoclePlugin/types/PortletSearch/query.jsp
Ajout d'un attribut récupéré par le module SEO.
Permet de générer un meta robot en "noindex, nofollow" en cas de besoin.
Ici : pour les pages de résultats de recherche (moteur général + recherche facette).
=> FIx : optimisation SEO (RS-1581)

plugins/SoclePlugin/jsp/portal/calculetteOA.jsp, plugins/SoclePlugin/jsp/portal/socialNetworksFooter.jspf, plugins/SoclePlugin/types/PortletAgendaInfolocale/doPortletAgendaInfolocaleFacettes.jsp, plugins/SoclePlugin/types/PortletFacetteAgendaDate/doPortletFacetteAgendaDateBoxDisplay.jsp, plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesBoxDisplay.jsp
https://refonte44.atlassian.net/browse/RS-1580
Pour `doPortletFacetteAgendaDateBoxDisplay.jsp`, il y a beaucoup de modif qui sont juste des rajouts à la ligne et de l'indentation. Y a peut-être moyen d'y voir plus clair en cachant les "whitespace changes". 
Je devai juste corriger les title des inputs des jours/mois/années de début et de fin de période ; mais les erreurs étaient sur des lignes _très_ longues (La plus longue ligne faisait 2387 caractères !). Ces modifs sont lignes 84 à 102 et lignes 129 à 147.
J'ai aussi mis des `glp()` à la place de textes laissés en dur ligne 151 et 155 ; et j'ai viré tous les "form-element" qui étaient en double dans les id.
> Dans la vérification HTML, il reste une erreur dans une balise script. Suite à ma discussion avec Stéphane, j'attends que Franck …
=> FIX RS-1580 erreurs verif html

WEB-INF/tags/tuileContenuEnAvant.tag, plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp, plugins/SoclePlugin/jsp/templates/tuileVerticale.jsp, plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf, plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselSliderSixPanels.jsp
Au final, malgré ce qui m'a été dit, il faut vider complètement le champ 'alt' dans tous les cas pour les images où il n'y a pas de figcaption (tuiles en avant, verticales, horizontales)
=> 1500 - retirer contenu "alt" tuiles sans figcaption

plugins/SoclePlugin/jsp/portal/posezUneQuestion.jsp
Ne pas afficher le bouton sur les fiches aide en mode "small device".
Ajout d'une classe pour traiter le pb en responsif.
=> Hotfix sticky button "posez une question" (RS-1571)

WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, plugins/SoclePlugin/jsp/templates/fileDocumentEmbedTemplate.jsp, plugins/SoclePlugin/types/FicheActionEducative/doFicheActionEducativeFullDisplay.jsp, plugins/SoclePlugin/types/FicheAide/doFicheAideFullDisplay.jsp, plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp, plugins/SoclePlugin/types/FichePublication/doFichePublicationFullDisplay.jsp, plugins/SoclePlugin/types/FileDocument/doFileDocumentEmbedDisplay.jsp, plugins/SoclePlugin/types/FileDocument/doFileDocumentFullDisplay.jsp, plugins/SoclePlugin/types/ListeDeContenus/doListeDeContenusDocuments.jsp, plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateMenuCollapseFullDisplay.jsp
Supprime l'abbréviation lors de l'affichage du poids du fichier.
renommage d'un label de title de bouton (fiche aide).
=> hotfix RS-1627

WEB-INF/data/types/FaqAccueil/FaqAccueil.xml
https://refonte44.atlassian.net/browse/RS-1662
les gabarits d'FAQAccueil avaient déjà des `userlang` partout, rien à retoucher de ce côté là
=> EVOL RS-1662 passage multilangue type FAQAccueil

WEB-INF/classes/fr/cg44/plugin/socle/LiensUtils.java, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
Encoder le mailto:? et autres paramètres causait soucis. Nul besoin d'encoder l'URL dans le paramètre normalement (censé être déjà encodé pour) mais laissé au cas où. Ca passe avec et sans de mon côté sur ThunderBird.
=> 1638 - Fix lien mailto partage par mail

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/portal/headerSection.jsp
Ajout d'une prop pour indiquer si le site est multilingue ou non
Ajout de prop pour les libellés
Gestion du changement de langue dans le fichier commun du header.
=> Evol : header multilingue

plugins/SoclePlugin/types/FaqAccueil/doFaqForm.jspf
Pour les sites GPLA (multilingues), le champ "commune" est libre et ne provient pas de la liste des communes JCMS (pas de restriction sur communes du dép).
Passage du champ pays en obligatoire.
=> Fix FAQ multilingue (RS-1673)

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java, WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/ContactFormDataController.java, WEB-INF/data/types/ContactForm/ContactForm.xml, WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, plugins/SoclePlugin/jsp/mail/formulaireContactTemplate.jsp, plugins/SoclePlugin/types/ContactForm/doEditContactForm.jsp
Champs différents en FR et EN, mais aussi entre la version FR multilingue et FR normale.
Type de formulaire unique mais gestion de ces cas de figure dans le gabarit de form + datacontroller
Refacto des objets de mail + suppression d'une prop inutile.
=> Fix formulaire contact (RS-1651)

WEB-INF/tags/titleBanner.tag
Ne pas mettre le nouveau champ "subtitle" obligatoire, car gros impact sur les gabarits existants
=> hotfix tag titleBanner

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop
Rajout de propriétés pour corriger un bug dans les envois de mail.
Ces props sont à surcharger dans custom.prop pour chaque site ayant un besoin de personnalisation de l'objet du mail.
=> Fix objet de mail

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java, WEB-INF/classes/fr/cg44/plugin/socle/infolocale/RequestManager.java, WEB-INF/plugins/SoclePlugin/properties/plugin.prop
Les métadonnées Infolocale ne peuvent être récupérées que sur un flux particulier. L'idée est de forcer cet ID de flux uniquement pour la récupération des thématiques personnalisées.
Inclut un fix pour le libellé des catégories agenda, et prend en compte la possibilité d'une donnée renvoyée en tant qu'array JSON et non pas en tant qu'objet.
Sera revu avec infolocale une fois un développeur revenu de congés de leur côté (mention d'une récupération possible via un autre endpoint)
Ce fix est proposé pour que la facette catégorie agenda soit fonctionnelle en production d'ici là.
=> Fix temporaire récupération thématiques perso

WEB-INF/classes/fr/cg44/plugin/socle/api/ApiNotesCacheManager.java
Correctif d'une maladresse assez stupide de ma part.
La récupération des notes Google doit être cependant revue. "Places" ne permet de récupérer que 5 reviews et pas la totalité sauf moyennant paiement. Des solutions semblent possible avec l'API Business.
=> 1736 - Fix API notes récupéraient mauvaises données

WEB-INF/data/types/FicheActu/FicheActu.xml, WEB-INF/data/types/FicheArticle/FicheArticle.xml
Pour alimenter le champ "Description" dans un flux RSS généré par jPlatform, il faut déclarer comme "abstract" un champ du type de contenu.
Pour le moment on ne cible que les FicheArticle  et FicheActu.
Le champ "chapo" est défini comme "abstract" (résumé).
=> Evol : ajout de l'attribut "abstract/résumé" sur 2 types de contenus

jcore/doEmptyHeader.jspf
Pour les mêmes meta le format large semble fonctionner sur d'autres sites.
Si cela ne fonctionne toujours pas, alors il faudra regarder ailleurs et comprendre pourquoi ça ne passe pas côté twitter...
Possibilité de blocage réseau ?
=> 979 - format twitter card large

WEB-INF/classes/fr/cg44/plugin/socle/VideoUtils.java
Le "return" semble empêcher l'include du composant "page utile" dans le fichier doFicheArticleFullDisplay.jsp.
En effet si les RS sont désactivés alors le composant page utile est masqué...
Du coup je l'ai remplacé et ça fonctionne bien comme ça.
=> Fix inclusion des RS bas de page

WEB-INF/plugins/SoclePlugin/plugin.xml, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/templates/tuileCommon.jsp, plugins/SoclePlugin/jsp/templates/tuileHorizontale.jsp, plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxOneColumnHomeExtraSmallTheme.jsp
Rajout d'un gabarit pour la portlet de mise en avant de contenu : tuile horizontale + petite et avec possibilité de mettre une couleur de fond.
Sera utilisé sur le site Observatoire.
=> EVOL RS-1780 gabarit "en un clic"

plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGrid.jsp, plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxOneColumn.jsp
Permet de prendre en compte la taille max paramétrée dans la portlet.
Evite ainsi les pb d'affichage et de temps de réponse quand la requête renvoie beaucoup de résultats
=> fix : prise en compte de la taille max du nb de résultats

WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/types/PortletMiseEnAvantDeContenus/doPortletMiseEnAvantDeContenusBoxGridIcon.jsp
Rajout d'un lien sur le logo "grand patrimoine". Non éditable. Lien pérenne.
Note : ce gabarit n'est utilisé que pour les sites patrimoniaux.
=> Evol portlet mise avant (RS-1826)

plugins/SoclePlugin/jsp/include/includePortletQueryForeachAlert.jsp
Ne pas afficher l'alerte lorsque le full display est appelé en affichage latéral gauche du moteur à facette.
=> evol : affichage alertes (RS-1836)

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java, WEB-INF/classes/fr/cg44/plugin/socle/infolocale/RequestManager.java
Auparavant, ne récupérait qu'une partie des métadonnées thématiques personnalisées. Le refacto prend également en compte les retours potentiels en jsonarray ou jsonobject (assez incertain jusque-là, les deux cas ont été rencontrés sur l'appel à /meta)
=> Refacto agenda récup thématiques perso

plugins/SoclePlugin/types/Lien/doLienFullDisplay.jsp
Empêche l'indexation par les moteur en générant un <meta name="robots" content="noindex, nofollow"/>
L'attribut envoyé est récupéré et traité par le module SEO.
=> hotfix : contenus de type Lien

WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/cards/doPublicationCard.jsp, plugins/SoclePlugin/jsp/facettes/displaySearchResult.jsp
Nouveau gabarit de tuile pour l'affichage des résultats du moteur de recherche général.
L'utilisation du tag <jalios:media> permet d'avoir un gabarit spécifique pour un type de contenu en cas de besoin.
Sera utilisé pour le site Observatoire.
=> Evol moteur de recherche général

plugins/SoclePlugin/types/PageCarrefour/doPageCarrefourFullDisplay.jsp, plugins/SoclePlugin/types/PortletRechercheFacettes/doPortletRechercheFacettesNoFacettesDisplay.jsp
Permet de mettre en bas d'une page carrefour une portlet de recherche à facette dont les résultats s'affinent sur la catégorie courante.
=> Evol page carrefour

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java, WEB-INF/data/types/PortletRechercheFacettes/PortletRechercheFacettes.xml, plugins/SoclePlugin/jsp/facettes/displayResult.jsp, plugins/SoclePlugin/jsp/portal/headerSection.jsp
Permet d'avoir un pager dans les recherche à facettes (non testé avec une carte).
Il y a un boolean dans la portlet recherche facette pour activer le pager (oui/non) pour l'utiliser simplement (valeur par défaut : "non").
Et correction d'un bug qui proposait un lien dans les raccourcis d'accessibilité vers la recherche même quand la recherche n'était pas présente sur le site.
=> Ajout de l'option pager dans la recherche à facettes

WEB-INF/plugins/SoclePlugin/wysiwyg/configuration-charteconfig.conf, plugins/SoclePlugin/wysiwyg/wysiwyg.css
- Permet de matérialiser le code HTML inséré via le module "EmbedPlugin", car dans certains cas on ne voir rien dans l'éditeur wysiwyg ce qui peut être perturbant (insertion de script par ex). Comme c'est assez spécifique je préfère ne pas mettre ça dans le DS.
- Correctif lien CSS pour éditeru wysiwyg. On le fait pointer vers le DS de dev qui est toujours + à jour (css+icones).
=> Evol : ajout de style pour éditeur wysiwyg

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java, WEB-INF/plugins/SoclePlugin/plugin.xml, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, WEB-INF/tags/figurePicture.tag
Prise en compte du ratio de l'image initiale pour générer la vignette. La largeur a été fixée à 370px.
=> Evol vignettes / format "custom" et "unchanged"

WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/PageUtileFormDataController.java, WEB-INF/plugins/SoclePlugin/plugin.xml, WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/plugins/SoclePlugin/properties/plugin.prop
Il existe déjà en JS un overlay de chargement qui attend la fin de la validation du formulaire (aka. le traitement Java complet)
Donc en théorie, le bouton devrait *déjà* être désactivé au clic. Voir s'il faut ajouter ce comportement pour d'autres contenus (par ex. le formulaire d'envoi de candidature)
=> 1085 - éviter les doublons form page utile

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateFooter.jsp
Appel de la modale Orejime via un lien "Cookies" présent en dernier élément des liens du footer.
Lien "en dur" car sera systématiquement placé en dernier sur tous les sites.
=> Lien cookies footer

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java
Eviter un IllegalStateException provoqué par un double .remove() sur l'iterator
=> Refacto duplicates agenda

WEB-INF/classes/fr/cg44/plugin/socle/MailUtils.java, WEB-INF/classes/fr/cg44/plugin/socle/datacontroller/InscriptionPressFormDataController.java, WEB-INF/data/types/InscriptionPressForm/InscriptionPressForm.xml, WEB-INF/plugins/SoclePlugin/plugin.xml, WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/plugins/SoclePlugin/properties/plugin.prop, plugins/SoclePlugin/jsp/doMessageBoxCustom.jspf, plugins/SoclePlugin/jsp/mail/formulaireEspacePresseConfirmationInscriptionTemplate.jsp, plugins/SoclePlugin/jsp/mail/formulaireEspacePresseDemandeConfirmationInscriptionTemplate.jsp, plugins/SoclePlugin/jsp/portal/doMessageBoxCustom.jsp, plugins/SoclePlugin/jsp/portal/inscription/valideInscriptionEspacePresse.jsp, plugins/SoclePlugin/types/InscriptionPressForm/doEditInscriptionPressForm.jsp, plugins/SoclePlugin/types/InscriptionPressForm/editFormInscriptionPressForm.jsp
Formulaire de demande de création de compte qui sera affiché à droite d'un article.
Principe de double opt-in : la demande déclenche l'envoi d'un mail contenant un lien de confirmation.
Suite confirmation, création du membre, ajout dans un groupe "Presse", attribution d'un mot de passe aléatoire et envoi des crédentiels par mail.
La soumission ne se fait pas en AJAX et ça peut être un point d'amélioration (à débattre).
J'ai fait une JSP "doMessageBox.jsp" pour pouvoir positionner une portlet JSP en tête de la colonne droite de l'article et ainsi afficher certains messages de succes/echec.
=> Inscription espace presse (RS-1744)

jcore/doEmptyHeader.jspf
Prévoir un suffixe personnalisé pour les titres de pages, à la place du channel.name.
Exploite les nouvelles propriétés du module SEO
=> Evol : titres de pages personnalisés

plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp
Utilisation de la méthode utilitaire dédiée car elle permet de récupérer l'id dans des URLs contenant plusieurs paramètres, et ainsi éviter des erreurs dans ce cas de figure.
Ex  : https://www.youtube.com/watch?time_continue=144&v=oS8ycF8ADbc&feature=emb_logo
=> Fix : récupération ID vidéo

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, plugins/SoclePlugin/jsp/portal/headerSection.jsp, plugins/SoclePlugin/types/PortletNavigate/doPortletNavigateBreadcrumb.jsp, plugins/SoclePlugin/types/Webdoc/doWebdocFullDisplay.jsp
- mettre en place un texte alternatif du logo différent entre la page d'accueil et les autres pages
- impact sur les autres pages renvoyant vers la Home
- refacto car plusieurs propriétés permettent de configurer un nom de site.
- Attention, dépendance avec SEOPlugin.
=> Evol : bouton Home (RS-1925)

WEB-INF/classes/fr/cg44/plugin/socle/SocleUtils.java, WEB-INF/plugins/SoclePlugin/plugin.xml, plugins/SoclePlugin/jsp/include/addFaqStructuredData.jsp, plugins/SoclePlugin/types/FaqAccueil/doFaqAccueilFullDisplayContent.jsp
Ajout de données structurées au format JSON sur les pages de FAQ.
Les données sont constituées dans le full display des FAQ puis envoyées sous forme d'attribut pour être affichées dans le "head" via une target.
=> Evol  : amélioration SEO pour les FAQ (RS-1913)

WEB-INF/data/types/FicheEmploiStage/FicheEmploiStage.xml, plugins/SoclePlugin/jsp/scripts/ficheEmploiStageActiviteToFuturesMissions.jsp, plugins/SoclePlugin/types/FicheEmploiStage/doFicheEmploiStageFullDisplay.jsp
Etape 1. La seconde étape supprimera le script et le champ "Activités"
=> 2030 - transfert activités vers missions fiche emploi stage

WEB-INF/classes/fr/cg44/plugin/socle/ApiUtil.java
L'encodage de toute l'URL pose problème dans certains cas. Si besoin il faudra encoder en amont les éventuels paramètres.
=> Fix appels api

plugins/SoclePlugin/types/AccueilAnnuaireAgenda/doAccueilAnnuaireAgenda_Agenda.jsp, plugins/SoclePlugin/types/AccueilDelegation/doAccueilDelegationFullDisplay.jsp, plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf, plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselSliderSixPanels.jsp, plugins/SoclePlugin/types/PortletConteneurAgenda/doPortletConteneurAgendaBoxDisplay.jsp
Le <jalios:wysiwyg> générait un div, qui ne peut être placé dans un p. Par conséquent, le div était placé à côté et le CSS via style ne pouvait plus être appliqué
Passage en ligne unique
=> 2037 - Fix regression display sous-titre

WEB-INF/plugins/SoclePlugin/properties/languages/en.prop, WEB-INF/plugins/SoclePlugin/properties/languages/fr.prop, WEB-INF/tags/titleSimple.tag, plugins/SoclePlugin/jsp/rgpd/orejimeConfig.jsp, plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp
Chapitrage désactivé car le code JS actuel cause soucis. On ne peut avoir que l'un ou l'autre pour le moment. L'overlay est prioritaire.
=> 1974 - Overlay GRPD vidéo - désactivation chapitrage

WEB-INF/tags/titleSimple.tag, plugins/SoclePlugin/types/Video/doVideoEmbedDisplay.jsp
Pour conformité code HTML DS (balise "i" après le "span" et pas dedans).
=> Fix bouton overlay vidéo

WEB-INF/classes/fr/cg44/plugin/socle/ApiUtil.java, WEB-INF/classes/fr/cg44/plugin/socle/infolocale/RequestManager.java, WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java, WEB-INF/plugins/SoclePlugin/properties/plugin.prop
→ le comportement semble ne pas différer entre la 1.3 et la 2.1.
Des champs supplémentaires, mais inutilisés, ont été ajoutés aux contenus “événements”
Fonctionnellement la même chose présentement
=> Montée version 1.3 -> 2.1 infolocale

plugins/SoclePlugin/jsp/portal/blocMenuPDCV.jspf
Suppression d'un aria-hidden invalide pour cette balise. Conformité avec le DS.
=> Fix accessibilité. Menu PDCV

plugins/SoclePlugin/types/PortletCarousel/doPortletCarouselBoxDisplay.jspf
Mise en buffer des résultats avant affichage. En faisant l'affichage direct, les résultats etaient nuls, dans le contexte d'une portlet carrousel générée dynamiquement dans un gabrit full par ex.
=> Fix : portlet carrousel

jcore/doEmptyHeader.jspf
Si un contenu était en BDD on essayait de récupérer son extradata (ce qui n'est pas autorisé)
Passage de isInDatabase() vers isDBData() pour la cohérence
=> Quickfix SEO anomalie sur contenus BDD

plugins/SoclePlugin/jsp/reprise/repriseFicheLieu.jsp
Dans la conversion des "Place" en "Fiche Lieu", il y avait un bug sur le setter de l'extradatada.
=> Fix : reprise des fiche lieu

plugins/SoclePlugin/jsp/facettes/displayResult.jsp
Les contenus en accès restreint ne sont pas affichés, même si on est connecté. En effet, l'utilisateur courant n'est pas transmis au Query handler.
NOTE : correctif à appliquer sans doutes dans d'autres fichiers car le loggedMember ne semble pas souvent passé aux différents QueryHandler.
=> Fix : recherche par commune

WEB-INF/plugins/SoclePlugin/plugin.xml, WEB-INF/tags/box.tag
Ajout d'un tag pour la gestion des encadrés simples.
Permet de définir un type d'encadré : couleur thème / gris / alerte / bordure.
Permet d'avoir un titre, préciser un aria-level, une légende, et des classes spécifiques.
Je m'en sers pour Assmat. J'en avais marre de copier/coller le même code plusieurs fois.
=> Evol : tag pour encadrés

plugins/SoclePlugin/jsp/portal/centeredColumnPortal.jsp
Nouveau gabarit qui servira pour Assmat. Simple colonne principale, centrée, sans colonnes gauche/droite.
Le gabarit des pages carrefour, un peu similaire, ne convenait pas. Mis dans Socle volontairement.
=> Evol : gabarit de portail centré

WEB-INF/classes/fr/cg44/plugin/socle/channellistener/SocleChannelListener.java
Active le listener par défaut mais donne la possibilité de le désactiver pour les sites ne contenant pas d'agenda. Evite les erreurs lorsque le site n'est pas autorisé à appeler l'API.
=> Evol : InfolocaleAlarmListener

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/InfolocaleEntityUtils.java
Champ String en V1, champ int en V2 pour "id" sur les thématiques personnalisées
Prise en compte V1 / V2 selon la valeur de l'URL de l'API. "/v2/" est la signature d'accès à l'API V2
=> Prise en compte format différent champ json id thematique perso

plugins/SoclePlugin/jsp/api/getHtml.jsp
JSP permettant de récupérer le code HTML de la zone wysiwyg d'une portlet Wysiwyg. Sert dans le cadre du site de l'Animation Sportive Départementale pour récupérer ce code et l'afficher sur le site.
=> Feat : récupérer le code HTML d'une portlet Wysiwyg

WEB-INF/classes/fr/cg44/plugin/socle/infolocale/util/InfolocaleUtil.java, plugins/SoclePlugin/types/EvenementInfolocale/doEvenementInfolocaleFullDisplay.jsp
Retournait toujours les horaires de la première date sur un fulldisplay, même si on affichait les informations de la date 2 par ex.
=> Quickfix erreur display horaires fulldisplay infolocale

plugins/SoclePlugin/types/FicheLieu/doFicheLieuFullDisplay.jsp
Juste un changement de condition sur un full display pour correspondre à la demande du ticket
Le CS indiqué dans le type est utilisé à la fois dans une adresse et dans l'autre. J'ai conservé l'ancienne condition pour raison d'historique, bien que celle-ci ne soit logiquement pas nécessaire...
=> RS-2120 - cacher CS adresse physique si à écrire existe fiche lieu

WEB-INF/classes/fr/cg44/plugin/socle/bean/SectorResult.java
Certains champs peuvent être nuls et provoquer une exception.
=> Hotfix : [Oreco] tester la validité des champs
